/**
 * @file wiring_irq.h
 * @author Daniel Starke
 * @copyright Copyright 2020-2022 Daniel Starke
 * @date 2020-11-13
 * @version 2022-04-03
 * 
 * @internal For internal use only.
 */
#ifndef __WIRING_IRQ_H__
#define __WIRING_IRQ_H__


#if defined(STM32CUBEDUINO_CUSTOM_IRQ_HANDLERS) && defined(STM32CUBEDUINO_MAP_ALL_IRQS)
#error STM32CUBEDUINO_CUSTOM_IRQ_HANDLERS and STM32CUBEDUINO_MAP_ALL_IRQS cannot be defined together.
#endif /* STM32CUBEDUINO_CUSTOM_IRQ_HANDLERS and STM32CUBEDUINO_MAP_ALL_IRQS */


/* Ensure that there are no macro re-mappings enabled. */
#undef ADC_IRQn
#undef ADC1_COMP_IRQn
#undef ADC1_IRQn
#undef ADC1_2_IRQn
#undef ADC2_IRQn
#undef ADC3_IRQn
#undef ADC4_IRQn
#undef ADC5_IRQn

#undef AES_IRQn
#undef AES_RNG_IRQn
#undef AES_RNG_LPUART1_IRQn
#undef AES1_IRQn
#undef AES2_IRQn

#undef BDMA_Channel0_IRQn
#undef BDMA_Channel1_IRQn
#undef BDMA_Channel2_IRQn
#undef BDMA_Channel3_IRQn
#undef BDMA_Channel4_IRQn
#undef BDMA_Channel5_IRQn
#undef BDMA_Channel6_IRQn
#undef BDMA_Channel7_IRQn
#undef BDMA1_IRQn
#undef BDMA2_Channel0_IRQn
#undef BDMA2_Channel1_IRQn
#undef BDMA2_Channel2_IRQn
#undef BDMA2_Channel3_IRQn
#undef BDMA2_Channel4_IRQn
#undef BDMA2_Channel5_IRQn
#undef BDMA2_Channel6_IRQn
#undef BDMA2_Channel7_IRQn

#undef BusFault_IRQn

#undef CAN_RX0_IRQn
#undef CAN_RX1_IRQn
#undef CAN_SCE_IRQn
#undef CAN_TX_IRQn
#undef CAN1_RX0_IRQn
#undef CAN1_RX1_IRQn
#undef CAN1_SCE_IRQn
#undef CAN1_TX_IRQn
#undef CAN2_RX0_IRQn
#undef CAN2_RX1_IRQn
#undef CAN2_SCE_IRQn
#undef CAN2_TX_IRQn
#undef CAN3_RX0_IRQn
#undef CAN3_RX1_IRQn
#undef CAN3_SCE_IRQn
#undef CAN3_TX_IRQn

#undef CEC_CAN_IRQn
#undef CEC_IRQn

#undef CM4_SEV_IRQn
#undef CM7_SEV_IRQn

#undef COMP_ACQ_IRQn
#undef COMP_IRQn
#undef COMP1_2_IRQn
#undef COMP1_2_3_IRQn
#undef COMP2_IRQn
#undef COMP4_IRQn
#undef COMP4_5_6_IRQn
#undef COMP4_6_IRQn
#undef COMP7_IRQn

#undef CORDIC_IRQn

#undef CRS_IRQn

#undef CRYP_IRQn
#undef CRYP1_IRQn
#undef CRYP2_IRQn

#undef C2SEV_PWR_C2H_IRQn

#undef DAC_IRQn
#undef DAC2_IRQn

#undef DCMI_IRQn
#undef DCMI_PSSI_IRQn

#undef DFSDM1_FLT0_IRQn
#undef DFSDM1_FLT1_IRQn
#undef DFSDM1_FLT2_IRQn
#undef DFSDM1_FLT3_IRQn
#undef DFSDM1_FLT4_IRQn
#undef DFSDM1_FLT5_IRQn
#undef DFSDM1_FLT6_IRQn
#undef DFSDM1_FLT7_IRQn
#undef DFSDM2_FLT0_IRQn
#undef DFSDM2_FLT1_IRQn
#undef DFSDM2_FLT2_IRQn
#undef DFSDM2_FLT3_IRQn
#undef DFSDM2_IRQn

#undef DMAMUX_OVR_IRQn
#undef DMAMUX1_IRQn
#undef DMAMUX1_OVR_IRQn
#undef DMAMUX1_S_IRQn
#undef DMAMUX2_OVR_IRQn

#undef DMA1_Channel1_IRQn
#undef DMA1_Channel2_IRQn
#undef DMA1_Channel2_3_IRQn
#undef DMA1_Channel3_IRQn
#undef DMA1_Channel4_IRQn
#undef DMA1_Channel4_5_IRQn
#undef DMA1_Channel4_5_6_7_IRQn
#undef DMA1_Channel5_IRQn
#undef DMA1_Channel6_IRQn
#undef DMA1_Channel7_IRQn
#undef DMA1_Channel8_IRQn
#undef DMA1_Ch1_IRQn
#undef DMA1_Ch2_3_DMA2_Ch1_2_IRQn
#undef DMA1_Ch4_5_DMAMUX1_OVR_IRQn
#undef DMA1_Ch4_7_DMAMUX1_OVR_IRQn
#undef DMA1_Ch4_7_DMA2_Ch3_5_IRQn
#undef DMA1_Stream0_IRQn
#undef DMA1_Stream1_IRQn
#undef DMA1_Stream2_IRQn
#undef DMA1_Stream3_IRQn
#undef DMA1_Stream4_IRQn
#undef DMA1_Stream5_IRQn
#undef DMA1_Stream6_IRQn
#undef DMA1_Stream7_IRQn
#undef DMA2D_IRQn
#undef DMA2_Channel1_IRQn
#undef DMA2_Channel2_IRQn
#undef DMA2_Channel3_IRQn
#undef DMA2_Channel4_IRQn
#undef DMA2_Channel4_5_IRQn
#undef DMA2_Channel5_IRQn
#undef DMA2_Channel6_IRQn
#undef DMA2_Channel7_IRQn
#undef DMA2_Channel8_IRQn
#undef DMA2_Stream0_IRQn
#undef DMA2_Stream1_IRQn
#undef DMA2_Stream2_IRQn
#undef DMA2_Stream3_IRQn
#undef DMA2_Stream4_IRQn
#undef DMA2_Stream5_IRQn
#undef DMA2_Stream6_IRQn
#undef DMA2_Stream7_IRQn

#undef DSI_IRQn

#undef DTS_IRQn

#undef DebugMonitor_IRQn

#undef ECC_IRQn

#undef ETH_IRQn
#undef ETH_WKUP_IRQn
#undef ETH1_IRQn
#undef ETH1_LPI_IRQn
#undef ETH1_WKUP_IRQn

#undef EXTI0_IRQn
#undef EXTI0_1_IRQn
#undef EXTI1_IRQn
#undef EXTI2_IRQn
#undef EXTI2_TSC_IRQn
#undef EXTI2_3_IRQn
#undef EXTI3_IRQn
#undef EXTI4_IRQn
#undef EXTI4_15_IRQn
#undef EXTI5_IRQn
#undef EXTI6_IRQn
#undef EXTI7_IRQn
#undef EXTI8_IRQn
#undef EXTI9_IRQn
#undef EXTI9_5_IRQn
#undef EXTI10_IRQn
#undef EXTI11_IRQn
#undef EXTI12_IRQn
#undef EXTI13_IRQn
#undef EXTI14_IRQn
#undef EXTI15_IRQn
#undef EXTI15_10_IRQn

#undef FDCAN_CAL_IRQn
#undef FDCAN1_IT0_IRQn
#undef FDCAN1_IT1_IRQn
#undef FDCAN2_IT0_IRQn
#undef FDCAN2_IT1_IRQn
#undef FDCAN3_IT0_IRQn
#undef FDCAN3_IT1_IRQn

#undef FLASH_IRQn
#undef FLASH_S_IRQn

#undef FMAC_IRQn

#undef FMC_IRQn

#undef FMPI2C1_ER_IRQn
#undef FMPI2C1_EV_IRQn

#undef FPU_IRQn

#undef FSMC_IRQn

#undef GFXMMU_IRQn

#undef GPU_IRQn

#undef GTZC_IRQn

#undef HASH_CRS_IRQn
#undef HASH_IRQn
#undef HASH_RNG_IRQn
#undef HASH1_IRQn
#undef HASH2_IRQn

#undef HOLD_CORE_IRQn

#undef HRTIM1_FLT_IRQn
#undef HRTIM1_Master_IRQn
#undef HRTIM1_TIMA_IRQn
#undef HRTIM1_TIMB_IRQn
#undef HRTIM1_TIMC_IRQn
#undef HRTIM1_TIMD_IRQn
#undef HRTIM1_TIME_IRQn
#undef HRTIM1_TIMF_IRQn

#undef HSEM_IRQn
#undef HSEM_IT2_IRQn
#undef HSEM1_IRQn
#undef HSEM2_IRQn

#undef HardFault_IRQn

#undef ICACHE_IRQn

#undef IPCC_C1_RX_IRQn
#undef IPCC_C1_TX_IRQn
#undef IPCC_RX0_IRQn
#undef IPCC_RX1_IRQn
#undef IPCC_TX0_IRQn
#undef IPCC_TX1_IRQn

#undef I2C1_ER_IRQn
#undef I2C1_EV_IRQn
#undef I2C1_IRQn
#undef I2C2_ER_IRQn
#undef I2C2_EV_IRQn
#undef I2C2_IRQn
#undef I2C3_ER_IRQn
#undef I2C3_EV_IRQn
#undef I2C3_IRQn
#undef I2C4_ER_IRQn
#undef I2C4_EV_IRQn
#undef I2C5_ER_IRQn
#undef I2C5_EV_IRQn
#undef I2C6_ER_IRQn
#undef I2C6_EV_IRQn

#undef JPEG_IRQn

#undef LCD_IRQn

#undef LPTIM1_IRQn
#undef LPTIM2_IRQn
#undef LPTIM3_IRQn
#undef LPTIM4_IRQn
#undef LPTIM5_IRQn

#undef LPUART1_IRQn

#undef LTDC_ER_IRQn
#undef LTDC_IRQn

#undef MDIOS_IRQn
#undef MDIOS_WKUP_IRQn

#undef MDMA_IRQn

#undef MPU_SEV_IRQn

#undef MemoryManagement_IRQn

#undef NonMaskableInt_IRQn

#undef OCTOSPI1_IRQn
#undef OCTOSPI2_IRQn

#undef OTFDEC1_IRQn
#undef OTFDEC2_IRQn

#undef OTG_FS_EP1_IN_IRQn
#undef OTG_FS_EP1_OUT_IRQn
#undef OTG_FS_IRQn
#undef OTG_FS_WKUP_IRQn
#undef OTG_HS_EP1_IN_IRQn
#undef OTG_HS_EP1_OUT_IRQn
#undef OTG_HS_IRQn
#undef OTG_HS_WKUP_IRQn
#undef OTG_IRQn

#undef PKA_IRQn

#undef PVD_AVD_IRQn
#undef PVD_IRQn
#undef PVD_PVM_IRQn
#undef PVD_VDDIO2_IRQn

#undef PWR_SOTF_BLEACT_802ACT_RFPHASE_IRQn

#undef PendSV_IRQn

#undef QUADSPI_IRQn

#undef RCC_CRS_IRQn
#undef RCC_IRQn
#undef RCC_S_IRQn
#undef RCC_WAKEUP_IRQn

#undef RNG_IRQn
#undef RNG_LPUART1_IRQn
#undef RNG1_IRQn
#undef RNG2_IRQn

#undef RTC_Alarm_IRQn
#undef RTC_IRQn
#undef RTC_S_IRQn
#undef RTC_TAMP_IRQn
#undef RTC_TAMP_LSECSS_IRQn
#undef RTC_TAMP_STAMP_CSS_LSE_IRQn
#undef RTC_TIMESTAMP_IRQn
#undef RTC_WKUP_ALARM_IRQn
#undef RTC_WKUP_IRQn

#undef SAI1_IRQn
#undef SAI2_IRQn
#undef SAI3_IRQn
#undef SAI4_IRQn

#undef SDADC1_IRQn
#undef SDADC2_IRQn
#undef SDADC3_IRQn

#undef SDIO_IRQn

#undef SDMMC1_IRQn
#undef SDMMC2_IRQn
#undef SDMMC3_IRQn

#undef SPDIF_RX_IRQn

#undef SPI1_IRQn
#undef SPI2_IRQn
#undef SPI3_IRQn
#undef SPI4_IRQn
#undef SPI5_IRQn
#undef SPI6_IRQn

#undef SVC_IRQn

#undef SVCall_IRQn

#undef SWPMI1_IRQn

#undef SecureFault_IRQn

#undef SysTick_IRQn

#undef TAMPER_IRQn
#undef TAMPER_STAMP_IRQn

#undef TAMP_IRQn
#undef TAMP_STAMP_IRQn
#undef TAMP_STAMP_LSECSS_IRQn
#undef TAMP_S_IRQn

#undef TEMP_IRQn

#undef TIM1_BRK_IRQn
#undef TIM1_BRK_TIM9_IRQn
#undef TIM1_BRK_TIM15_IRQn
#undef TIM1_BRK_UP_TRG_COM_IRQn
#undef TIM1_CC_IRQn
#undef TIM1_TRG_COM_IRQn
#undef TIM1_TRG_COM_TIM11_IRQn
#undef TIM1_TRG_COM_TIM17_IRQn
#undef TIM1_UP_IRQn
#undef TIM1_UP_TIM10_IRQn
#undef TIM1_UP_TIM16_IRQn
#undef TIM2_IRQn
#undef TIM3_IRQn
#undef TIM4_IRQn
#undef TIM5_IRQn
#undef TIM6_DAC_IRQn
#undef TIM6_DAC_LPTIM1_IRQn
#undef TIM6_DAC1_IRQn
#undef TIM6_IRQn
#undef TIM7_DAC_IRQn
#undef TIM7_DAC2_IRQn
#undef TIM7_IRQn
#undef TIM7_LPTIM2_IRQn
#undef TIM8_BRK_IRQn
#undef TIM8_BRK_TIM12_IRQn
#undef TIM8_CC_IRQn
#undef TIM8_TRG_COM_IRQn
#undef TIM8_TRG_COM_TIM14_IRQn
#undef TIM8_UP_IRQn
#undef TIM8_UP_TIM13_IRQn
#undef TIM9_IRQn
#undef TIM10_IRQn
#undef TIM11_IRQn
#undef TIM12_IRQn
#undef TIM13_IRQn
#undef TIM14_IRQn
#undef TIM15_IRQn
#undef TIM16_IRQn
#undef TIM17_IRQn
#undef TIM18_DAC2_IRQn
#undef TIM19_IRQn
#undef TIM20_BRK_IRQn
#undef TIM20_CC_IRQn
#undef TIM20_TRG_COM_IRQn
#undef TIM20_UP_IRQn
#undef TIM21_IRQn
#undef TIM22_IRQn
#undef TIM23_IRQn
#undef TIM24_IRQn

#undef TSC_IRQn

#undef UART4_IRQn
#undef UART5_IRQn
#undef UART7_IRQn
#undef UART8_IRQn
#undef UART9_IRQn
#undef UART10_IRQn

#undef UCPD1_IRQn
#undef UCPD1_2_IRQn

#undef USART1_IRQn
#undef USART2_IRQn
#undef USART3_IRQn
#undef USART3_4_IRQn
#undef USART3_4_LPUART1_IRQn
#undef USART3_6_IRQn
#undef USART3_8_IRQn
#undef USART4_5_IRQn
#undef USART6_IRQn
#undef USART10_IRQn

#undef USBH_EHCI_IRQn
#undef USBH_OHCI_IRQn

#undef USBWakeUp_IRQn
#undef USBWakeUp_RMP_IRQn

#undef USB_FS_IRQn
#undef USB_FS_WKUP_IRQn
#undef USB_HP_CAN_TX_IRQn
#undef USB_HP_CAN1_TX_IRQn
#undef USB_HP_IRQn
#undef USB_IRQn
#undef USB_LP_CAN_RX0_IRQn
#undef USB_LP_CAN1_RX0_IRQn
#undef USB_LP_IRQn

#undef UsageFault_IRQn

#undef VDDIO2_IRQn

#undef WAKEUP_PIN_IRQn

#undef WWDG_IRQn
#undef WWDG_RST_IRQn
#undef WWDG1_IRQn

#undef nCTIIRQ1_IRQn
#undef nCTIIRQ2_IRQn


/* C++ SFINAE for selecting the right IRQn */
/**
 * Defines a getIrqNumForXXX() function overload which returns the given IRQn for
 * the passed STM32 HAL instance, if such an IRQ exists.
 * 
 * @param[in] INST - STM32 HAL instance
 * @param[in] IRQn - STM32 HAL IRQ number
 * @internal Use getIrqNumFor() to obtain a specific IRQ number of a given STM32 HAL instance.
 */
#define __DEF_GET_IRQ(INST, IRQn) \
	template <typename T> \
	constexpr static inline IRQn_Type getIrqNumFor##INST(decltype(T::IRQn) *) { \
		return T::IRQn; \
	}

/**
 * Returns the IRQ number for the given STM32 HAL instance.
 * 
 * @param[in] INST - STM32 HAL instance
 * @return corresponding IRQ number or linker error
 */
#define getIrqNumFor(INST) getIrqNumFor##INST<IRQn_Type>(0)


/* Map IRQs to the possible associated STM32 HAL instances for all IRQs available. */
__DEF_GET_IRQ(ADC1, ADC_IRQn)
__DEF_GET_IRQ(ADC2, ADC_IRQn)
__DEF_GET_IRQ(ADC3, ADC_IRQn)

__DEF_GET_IRQ(ADC, ADC1_COMP_IRQn)
__DEF_GET_IRQ(ADC1, ADC1_COMP_IRQn)
__DEF_GET_IRQ(COMP1, ADC1_COMP_IRQn)
__DEF_GET_IRQ(COMP2, ADC1_COMP_IRQn)

__DEF_GET_IRQ(ADC, ADC1_IRQn)
__DEF_GET_IRQ(ADC1, ADC1_IRQn)

__DEF_GET_IRQ(ADC1, ADC1_2_IRQn)
__DEF_GET_IRQ(ADC2, ADC1_2_IRQn)

__DEF_GET_IRQ(ADC2, ADC2_IRQn)

__DEF_GET_IRQ(ADC3, ADC3_IRQn)

__DEF_GET_IRQ(ADC4, ADC4_IRQn)

__DEF_GET_IRQ(ADC5, ADC5_IRQn)

__DEF_GET_IRQ(AES, AES_IRQn)

__DEF_GET_IRQ(AES, AES_RNG_IRQn)
__DEF_GET_IRQ(RNG, AES_RNG_IRQn)

__DEF_GET_IRQ(AES, AES_RNG_LPUART1_IRQn)
__DEF_GET_IRQ(LPUART1, AES_RNG_LPUART1_IRQn)
__DEF_GET_IRQ(RNG, AES_RNG_LPUART1_IRQn)

__DEF_GET_IRQ(AES1, AES1_IRQn)

__DEF_GET_IRQ(AES2, AES2_IRQn)

__DEF_GET_IRQ(BDMA_CH0, BDMA_Channel0_IRQn)
__DEF_GET_IRQ(BDMA2_CH0, BDMA_Channel0_IRQn)

__DEF_GET_IRQ(BDMA_CH1, BDMA_Channel1_IRQn)
__DEF_GET_IRQ(BDMA2_CH1, BDMA_Channel1_IRQn)

__DEF_GET_IRQ(BDMA_CH2, BDMA_Channel2_IRQn)
__DEF_GET_IRQ(BDMA2_CH2, BDMA_Channel2_IRQn)

__DEF_GET_IRQ(BDMA_CH3, BDMA_Channel3_IRQn)
__DEF_GET_IRQ(BDMA2_CH3, BDMA_Channel3_IRQn)

__DEF_GET_IRQ(BDMA_CH4, BDMA_Channel4_IRQn)
__DEF_GET_IRQ(BDMA2_CH4, BDMA_Channel4_IRQn)

__DEF_GET_IRQ(BDMA_CH5, BDMA_Channel5_IRQn)
__DEF_GET_IRQ(BDMA2_CH5, BDMA_Channel5_IRQn)

__DEF_GET_IRQ(BDMA_CH6, BDMA_Channel6_IRQn)
__DEF_GET_IRQ(BDMA2_CH6, BDMA_Channel6_IRQn)

__DEF_GET_IRQ(BDMA_CH7, BDMA_Channel7_IRQn)
__DEF_GET_IRQ(BDMA2_CH7, BDMA_Channel7_IRQn)

__DEF_GET_IRQ(BDMA1_CH0, BDMA1_IRQn)
__DEF_GET_IRQ(BDMA1_CH1, BDMA1_IRQn)
__DEF_GET_IRQ(BDMA1_CH2, BDMA1_IRQn)
__DEF_GET_IRQ(BDMA1_CH3, BDMA1_IRQn)
__DEF_GET_IRQ(BDMA1_CH4, BDMA1_IRQn)
__DEF_GET_IRQ(BDMA1_CH5, BDMA1_IRQn)
__DEF_GET_IRQ(BDMA1_CH6, BDMA1_IRQn)
__DEF_GET_IRQ(BDMA1_CH7, BDMA1_IRQn)

__DEF_GET_IRQ(BDMA2_CH0, BDMA2_Channel0_IRQn)

__DEF_GET_IRQ(BDMA2_CH1, BDMA2_Channel1_IRQn)

__DEF_GET_IRQ(BDMA2_CH2, BDMA2_Channel2_IRQn)

__DEF_GET_IRQ(BDMA2_CH3, BDMA2_Channel3_IRQn)

__DEF_GET_IRQ(BDMA2_CH4, BDMA2_Channel4_IRQn)

__DEF_GET_IRQ(BDMA2_CH5, BDMA2_Channel5_IRQn)

__DEF_GET_IRQ(BDMA2_CH6, BDMA2_Channel6_IRQn)

__DEF_GET_IRQ(BDMA2_CH7, BDMA2_Channel7_IRQn)

__DEF_GET_IRQ(CAN, CAN_RX0_IRQn)

__DEF_GET_IRQ(CAN, CAN_RX1_IRQn)

__DEF_GET_IRQ(CAN, CAN_SCE_IRQn)

__DEF_GET_IRQ(CAN, CAN_TX_IRQn)

__DEF_GET_IRQ(CAN1, CAN1_RX0_IRQn)

__DEF_GET_IRQ(CAN, CAN1_RX1_IRQn)
__DEF_GET_IRQ(CAN1, CAN1_RX1_IRQn)

__DEF_GET_IRQ(CAN, CAN1_SCE_IRQn)
__DEF_GET_IRQ(CAN1, CAN1_SCE_IRQn)

__DEF_GET_IRQ(CAN1, CAN1_TX_IRQn)

__DEF_GET_IRQ(CAN2, CAN2_RX0_IRQn)

__DEF_GET_IRQ(CAN2, CAN2_RX1_IRQn)

__DEF_GET_IRQ(CAN2, CAN2_SCE_IRQn)

__DEF_GET_IRQ(CAN2, CAN2_TX_IRQn)

__DEF_GET_IRQ(CAN3, CAN3_RX0_IRQn)

__DEF_GET_IRQ(CAN3, CAN3_RX1_IRQn)

__DEF_GET_IRQ(CAN3, CAN3_SCE_IRQn)

__DEF_GET_IRQ(CAN3, CAN3_TX_IRQn)

__DEF_GET_IRQ(CAN, CEC_CAN_IRQn)
__DEF_GET_IRQ(HDMI_CEC, CEC_CAN_IRQn)

__DEF_GET_IRQ(HDMI_CEC, CEC_IRQn)

__DEF_GET_IRQ(COMP1, COMP_ACQ_IRQn)
__DEF_GET_IRQ(COMP2, COMP_ACQ_IRQn)

__DEF_GET_IRQ(COMP1, COMP_IRQn)
__DEF_GET_IRQ(COMP2, COMP_IRQn)

__DEF_GET_IRQ(COMP1, COMP1_2_IRQn)
__DEF_GET_IRQ(COMP2, COMP1_2_IRQn)

__DEF_GET_IRQ(COMP1, COMP1_2_3_IRQn)
__DEF_GET_IRQ(COMP2, COMP1_2_3_IRQn)
__DEF_GET_IRQ(COMP3, COMP1_2_3_IRQn)

__DEF_GET_IRQ(COMP2, COMP2_IRQn)

__DEF_GET_IRQ(COMP4, COMP4_IRQn)

__DEF_GET_IRQ(COMP4, COMP4_5_6_IRQn)
__DEF_GET_IRQ(COMP5, COMP4_5_6_IRQn)
__DEF_GET_IRQ(COMP6, COMP4_5_6_IRQn)

__DEF_GET_IRQ(COMP4, COMP4_6_IRQn)
__DEF_GET_IRQ(COMP6, COMP4_6_IRQn)

__DEF_GET_IRQ(COMP7, COMP7_IRQn)

__DEF_GET_IRQ(CORDIC, CORDIC_IRQn)

__DEF_GET_IRQ(RCC, CRS_IRQn)

__DEF_GET_IRQ(CRYP, CRYP_IRQn)

__DEF_GET_IRQ(CRYP1, CRYP1_IRQn)

__DEF_GET_IRQ(CRYP2, CRYP2_IRQn)

__DEF_GET_IRQ(DAC, DAC_IRQn)
__DEF_GET_IRQ(DAC1, DAC_IRQn)

__DEF_GET_IRQ(DAC2, DAC2_IRQn)

__DEF_GET_IRQ(DCMI, DCMI_IRQn)

__DEF_GET_IRQ(DCMI, DCMI_PSSI_IRQn)
__DEF_GET_IRQ(PSSI, DCMI_PSSI_IRQn)

__DEF_GET_IRQ(DFSDM1, DFSDM1_FLT0_IRQn)

__DEF_GET_IRQ(DFSDM1, DFSDM1_FLT1_IRQn)

__DEF_GET_IRQ(DFSDM1, DFSDM1_FLT2_IRQn)

__DEF_GET_IRQ(DFSDM1, DFSDM1_FLT3_IRQn)

__DEF_GET_IRQ(DFSDM1, DFSDM1_FLT4_IRQn)

__DEF_GET_IRQ(DFSDM1, DFSDM1_FLT5_IRQn)

__DEF_GET_IRQ(DFSDM1, DFSDM1_FLT6_IRQn)

__DEF_GET_IRQ(DFSDM1, DFSDM1_FLT7_IRQn)

__DEF_GET_IRQ(DFSDM2, DFSDM2_FLT0_IRQn)

__DEF_GET_IRQ(DFSDM2, DFSDM2_FLT1_IRQn)

__DEF_GET_IRQ(DFSDM2, DFSDM2_FLT2_IRQn)

__DEF_GET_IRQ(DFSDM2, DFSDM2_FLT3_IRQn)

__DEF_GET_IRQ(DFSDM2, DFSDM2_IRQn)

__DEF_GET_IRQ(DMA, DMAMUX_OVR_IRQn)

__DEF_GET_IRQ(DMA, DMAMUX1_IRQn)

__DEF_GET_IRQ(DMA, DMAMUX1_OVR_IRQn)

__DEF_GET_IRQ(DMA, DMAMUX1_S_IRQn)

__DEF_GET_IRQ(BDMA, DMAMUX2_OVR_IRQn)
__DEF_GET_IRQ(BDMA2, DMAMUX2_OVR_IRQn)

__DEF_GET_IRQ(DMA1_CH1, DMA1_Channel1_IRQn)

__DEF_GET_IRQ(DMA1_CH2, DMA1_Channel2_IRQn)

__DEF_GET_IRQ(DMA1_CH2, DMA1_Channel2_3_IRQn)
__DEF_GET_IRQ(DMA1_CH3, DMA1_Channel2_3_IRQn)

__DEF_GET_IRQ(DMA1_CH3, DMA1_Channel3_IRQn)

__DEF_GET_IRQ(DMA1_CH4, DMA1_Channel4_IRQn)

__DEF_GET_IRQ(DMA1_CH4, DMA1_Channel4_5_IRQn)
__DEF_GET_IRQ(DMA1_CH5, DMA1_Channel4_5_IRQn)

__DEF_GET_IRQ(DMA1_CH4, DMA1_Channel4_5_6_7_IRQn)
__DEF_GET_IRQ(DMA1_CH5, DMA1_Channel4_5_6_7_IRQn)
__DEF_GET_IRQ(DMA1_CH6, DMA1_Channel4_5_6_7_IRQn)
__DEF_GET_IRQ(DMA1_CH7, DMA1_Channel4_5_6_7_IRQn)

__DEF_GET_IRQ(DMA1_CH5, DMA1_Channel5_IRQn)

__DEF_GET_IRQ(DMA1_CH6, DMA1_Channel6_IRQn)

__DEF_GET_IRQ(DMA1_CH7, DMA1_Channel7_IRQn)

__DEF_GET_IRQ(DMA1_CH8, DMA1_Channel8_IRQn)

__DEF_GET_IRQ(DMA1_CH1, DMA1_Ch1_IRQn)

__DEF_GET_IRQ(DMA1_CH2, DMA1_Ch2_3_DMA2_Ch1_2_IRQn)
__DEF_GET_IRQ(DMA1_CH3, DMA1_Ch2_3_DMA2_Ch1_2_IRQn)
__DEF_GET_IRQ(DMA2_CH1, DMA1_Ch2_3_DMA2_Ch1_2_IRQn)
__DEF_GET_IRQ(DMA2_CH2, DMA1_Ch2_3_DMA2_Ch1_2_IRQn)

__DEF_GET_IRQ(DMA1_CH4, DMA1_Ch4_5_DMAMUX1_OVR_IRQn)
__DEF_GET_IRQ(DMA1_CH5, DMA1_Ch4_5_DMAMUX1_OVR_IRQn)

__DEF_GET_IRQ(DMA1_CH4, DMA1_Ch4_7_DMAMUX1_OVR_IRQn)
__DEF_GET_IRQ(DMA1_CH5, DMA1_Ch4_7_DMAMUX1_OVR_IRQn)
__DEF_GET_IRQ(DMA1_CH6, DMA1_Ch4_7_DMAMUX1_OVR_IRQn)
__DEF_GET_IRQ(DMA1_CH7, DMA1_Ch4_7_DMAMUX1_OVR_IRQn)

__DEF_GET_IRQ(DMA1_CH4, DMA1_Ch4_7_DMA2_Ch3_5_IRQn)
__DEF_GET_IRQ(DMA1_CH5, DMA1_Ch4_7_DMA2_Ch3_5_IRQn)
__DEF_GET_IRQ(DMA1_CH6, DMA1_Ch4_7_DMA2_Ch3_5_IRQn)
__DEF_GET_IRQ(DMA1_CH7, DMA1_Ch4_7_DMA2_Ch3_5_IRQn)
__DEF_GET_IRQ(DMA2_CH3, DMA1_Ch4_7_DMA2_Ch3_5_IRQn)
__DEF_GET_IRQ(DMA2_CH4, DMA1_Ch4_7_DMA2_Ch3_5_IRQn)
__DEF_GET_IRQ(DMA2_CH5, DMA1_Ch4_7_DMA2_Ch3_5_IRQn)

__DEF_GET_IRQ(DMA1_CH0, DMA1_Stream0_IRQn)

__DEF_GET_IRQ(DMA1_CH1, DMA1_Stream1_IRQn)

__DEF_GET_IRQ(DMA1_CH2, DMA1_Stream2_IRQn)

__DEF_GET_IRQ(DMA1_CH3, DMA1_Stream3_IRQn)

__DEF_GET_IRQ(DMA1_CH4, DMA1_Stream4_IRQn)

__DEF_GET_IRQ(DMA1_CH5, DMA1_Stream5_IRQn)

__DEF_GET_IRQ(DMA1_CH6, DMA1_Stream6_IRQn)

__DEF_GET_IRQ(DMA1_CH7, DMA1_Stream7_IRQn)

__DEF_GET_IRQ(DMA2D, DMA2D_IRQn)

__DEF_GET_IRQ(DMA2_CH1, DMA2_Channel1_IRQn)

__DEF_GET_IRQ(DMA2_CH2, DMA2_Channel2_IRQn)

__DEF_GET_IRQ(DMA2_CH3, DMA2_Channel3_IRQn)

__DEF_GET_IRQ(DMA2_CH4, DMA2_Channel4_IRQn)

__DEF_GET_IRQ(DMA2_CH4, DMA2_Channel4_5_IRQn)
__DEF_GET_IRQ(DMA2_CH5, DMA2_Channel4_5_IRQn)

__DEF_GET_IRQ(DMA2_CH5, DMA2_Channel5_IRQn)

__DEF_GET_IRQ(DMA2_CH6, DMA2_Channel6_IRQn)

__DEF_GET_IRQ(DMA2_CH7, DMA2_Channel7_IRQn)

__DEF_GET_IRQ(DMA2_CH8, DMA2_Channel8_IRQn)

__DEF_GET_IRQ(DMA2_CH0, DMA2_Stream0_IRQn)

__DEF_GET_IRQ(DMA2_CH1, DMA2_Stream1_IRQn)

__DEF_GET_IRQ(DMA2_CH2, DMA2_Stream2_IRQn)

__DEF_GET_IRQ(DMA2_CH3, DMA2_Stream3_IRQn)

__DEF_GET_IRQ(DMA2_CH4, DMA2_Stream4_IRQn)

__DEF_GET_IRQ(DMA2_CH5, DMA2_Stream5_IRQn)

__DEF_GET_IRQ(DMA2_CH6, DMA2_Stream6_IRQn)

__DEF_GET_IRQ(DMA2_CH7, DMA2_Stream7_IRQn)

__DEF_GET_IRQ(DSIHOST, DSI_IRQn)

__DEF_GET_IRQ(DTS, DTS_IRQn)

__DEF_GET_IRQ(ETH, ETH_IRQn)

__DEF_GET_IRQ(ETH, ETH_WKUP_IRQn)

__DEF_GET_IRQ(ETH1, ETH1_IRQn)

__DEF_GET_IRQ(ETH1, ETH1_LPI_IRQn)

__DEF_GET_IRQ(ETH1, ETH1_WKUP_IRQn)

__DEF_GET_IRQ(EXTI0, EXTI0_IRQn)

__DEF_GET_IRQ(EXTI0, EXTI0_1_IRQn)
__DEF_GET_IRQ(EXTI1, EXTI0_1_IRQn)

__DEF_GET_IRQ(EXTI1, EXTI1_IRQn)

__DEF_GET_IRQ(EXTI2, EXTI2_IRQn)

__DEF_GET_IRQ(EXTI2, EXTI2_TSC_IRQn)
__DEF_GET_IRQ(TSC, EXTI2_TSC_IRQn)

__DEF_GET_IRQ(EXTI2, EXTI2_3_IRQn)
__DEF_GET_IRQ(EXTI3, EXTI2_3_IRQn)

__DEF_GET_IRQ(EXTI3, EXTI3_IRQn)

__DEF_GET_IRQ(EXTI4, EXTI4_IRQn)

__DEF_GET_IRQ(EXTI4, EXTI4_15_IRQn)
__DEF_GET_IRQ(EXTI5, EXTI4_15_IRQn)
__DEF_GET_IRQ(EXTI6, EXTI4_15_IRQn)
__DEF_GET_IRQ(EXTI7, EXTI4_15_IRQn)
__DEF_GET_IRQ(EXTI8, EXTI4_15_IRQn)
__DEF_GET_IRQ(EXTI9, EXTI4_15_IRQn)
__DEF_GET_IRQ(EXTI10, EXTI4_15_IRQn)
__DEF_GET_IRQ(EXTI11, EXTI4_15_IRQn)
__DEF_GET_IRQ(EXTI12, EXTI4_15_IRQn)
__DEF_GET_IRQ(EXTI13, EXTI4_15_IRQn)
__DEF_GET_IRQ(EXTI14, EXTI4_15_IRQn)
__DEF_GET_IRQ(EXTI15, EXTI4_15_IRQn)

__DEF_GET_IRQ(EXTI5, EXTI5_IRQn)

__DEF_GET_IRQ(EXTI6, EXTI6_IRQn)

__DEF_GET_IRQ(EXTI7, EXTI7_IRQn)

__DEF_GET_IRQ(EXTI8, EXTI8_IRQn)

__DEF_GET_IRQ(EXTI9, EXTI9_IRQn)

__DEF_GET_IRQ(EXTI5, EXTI9_5_IRQn)
__DEF_GET_IRQ(EXTI6, EXTI9_5_IRQn)
__DEF_GET_IRQ(EXTI7, EXTI9_5_IRQn)
__DEF_GET_IRQ(EXTI8, EXTI9_5_IRQn)
__DEF_GET_IRQ(EXTI9, EXTI9_5_IRQn)

__DEF_GET_IRQ(EXTI10, EXTI10_IRQn)

__DEF_GET_IRQ(EXTI11, EXTI11_IRQn)

__DEF_GET_IRQ(EXTI12, EXTI12_IRQn)

__DEF_GET_IRQ(EXTI13, EXTI13_IRQn)

__DEF_GET_IRQ(EXTI14, EXTI14_IRQn)

__DEF_GET_IRQ(EXTI15, EXTI15_IRQn)

__DEF_GET_IRQ(EXTI10, EXTI15_10_IRQn)
__DEF_GET_IRQ(EXTI11, EXTI15_10_IRQn)
__DEF_GET_IRQ(EXTI12, EXTI15_10_IRQn)
__DEF_GET_IRQ(EXTI13, EXTI15_10_IRQn)
__DEF_GET_IRQ(EXTI14, EXTI15_10_IRQn)
__DEF_GET_IRQ(EXTI15, EXTI15_10_IRQn)

__DEF_GET_IRQ(FDCAN1, FDCAN_CAL_IRQn)
__DEF_GET_IRQ(FDCAN2, FDCAN_CAL_IRQn)

__DEF_GET_IRQ(FDCAN1, FDCAN1_IT0_IRQn)

__DEF_GET_IRQ(FDCAN1, FDCAN1_IT1_IRQn)

__DEF_GET_IRQ(FDCAN2, FDCAN2_IT0_IRQn)

__DEF_GET_IRQ(FDCAN2, FDCAN2_IT1_IRQn)

__DEF_GET_IRQ(FDCAN3, FDCAN3_IT0_IRQn)

__DEF_GET_IRQ(FDCAN3, FDCAN3_IT1_IRQn)

__DEF_GET_IRQ(FLASH, FLASH_IRQn)

__DEF_GET_IRQ(FLASH, FLASH_S_IRQn)

__DEF_GET_IRQ(FMAC, FMAC_IRQn)

__DEF_GET_IRQ(FMC, FMC_IRQn)

__DEF_GET_IRQ(FMPI2C1, FMPI2C1_ER_IRQn)

__DEF_GET_IRQ(FMPI2C1, FMPI2C1_EV_IRQn)

__DEF_GET_IRQ(FSMC, FSMC_IRQn)

__DEF_GET_IRQ(GFXMMU, GFXMMU_IRQn)

__DEF_GET_IRQ(GPU, GPU_IRQn)

__DEF_GET_IRQ(GTZC, GTZC_IRQn)

__DEF_GET_IRQ(HASH, HASH_CRS_IRQn)
__DEF_GET_IRQ(RCC, HASH_CRS_IRQn)

__DEF_GET_IRQ(HASH, HASH_IRQn)

__DEF_GET_IRQ(HASH, HASH_RNG_IRQn)
__DEF_GET_IRQ(RNG, HASH_RNG_IRQn)

__DEF_GET_IRQ(HASH1, HASH1_IRQn)

__DEF_GET_IRQ(HASH2, HASH2_IRQn)

__DEF_GET_IRQ(HRTIM, HRTIM1_FLT_IRQn)
__DEF_GET_IRQ(HRTIM1, HRTIM1_FLT_IRQn)

__DEF_GET_IRQ(HRTIM, HRTIM1_Master_IRQn)
__DEF_GET_IRQ(HRTIM1, HRTIM1_Master_IRQn)

__DEF_GET_IRQ(HRTIM, HRTIM1_TIMA_IRQn)
__DEF_GET_IRQ(HRTIM1, HRTIM1_TIMA_IRQn)

__DEF_GET_IRQ(HRTIM, HRTIM1_TIMB_IRQn)
__DEF_GET_IRQ(HRTIM1, HRTIM1_TIMB_IRQn)

__DEF_GET_IRQ(HRTIM, HRTIM1_TIMC_IRQn)
__DEF_GET_IRQ(HRTIM1, HRTIM1_TIMC_IRQn)

__DEF_GET_IRQ(HRTIM, HRTIM1_TIMD_IRQn)
__DEF_GET_IRQ(HRTIM1, HRTIM1_TIMD_IRQn)

__DEF_GET_IRQ(HRTIM, HRTIM1_TIME_IRQn)
__DEF_GET_IRQ(HRTIM1, HRTIM1_TIME_IRQn)

__DEF_GET_IRQ(HRTIM1, HRTIM1_TIMF_IRQn)

__DEF_GET_IRQ(HSEM, HSEM_IRQn)

__DEF_GET_IRQ(ICACHE, ICACHE_IRQn)

__DEF_GET_IRQ(IPCC, IPCC_C1_RX_IRQn)

__DEF_GET_IRQ(IPCC, IPCC_C1_TX_IRQn)

__DEF_GET_IRQ(IPCC, IPCC_RX0_IRQn)

__DEF_GET_IRQ(IPCC, IPCC_RX1_IRQn)

__DEF_GET_IRQ(IPCC, IPCC_TX0_IRQn)

__DEF_GET_IRQ(IPCC, IPCC_TX1_IRQn)

__DEF_GET_IRQ(I2C1, I2C1_ER_IRQn)

__DEF_GET_IRQ(I2C1, I2C1_EV_IRQn)

__DEF_GET_IRQ(I2C1, I2C1_IRQn)

__DEF_GET_IRQ(I2C2, I2C2_ER_IRQn)

__DEF_GET_IRQ(I2C2, I2C2_EV_IRQn)

__DEF_GET_IRQ(I2C2, I2C2_IRQn)

__DEF_GET_IRQ(I2C3, I2C3_ER_IRQn)

__DEF_GET_IRQ(I2C3, I2C3_EV_IRQn)

__DEF_GET_IRQ(I2C3, I2C3_IRQn)

__DEF_GET_IRQ(I2C4, I2C4_ER_IRQn)

__DEF_GET_IRQ(I2C4, I2C4_EV_IRQn)

__DEF_GET_IRQ(I2C5, I2C5_ER_IRQn)

__DEF_GET_IRQ(I2C5, I2C5_EV_IRQn)

__DEF_GET_IRQ(I2C6, I2C6_ER_IRQn)

__DEF_GET_IRQ(I2C6, I2C6_EV_IRQn)

__DEF_GET_IRQ(JPEG, JPEG_IRQn)

__DEF_GET_IRQ(LCD, LCD_IRQn)

__DEF_GET_IRQ(LPTIM1, LPTIM1_IRQn)

__DEF_GET_IRQ(LPTIM2, LPTIM2_IRQn)

__DEF_GET_IRQ(LPTIM3, LPTIM3_IRQn)

__DEF_GET_IRQ(LPTIM4, LPTIM4_IRQn)

__DEF_GET_IRQ(LPTIM5, LPTIM5_IRQn)

__DEF_GET_IRQ(LPUART1, LPUART1_IRQn)

__DEF_GET_IRQ(LTDC, LTDC_ER_IRQn)

__DEF_GET_IRQ(LTDC, LTDC_IRQn)

__DEF_GET_IRQ(MDIOS, MDIOS_IRQn)

__DEF_GET_IRQ(MDIOS, MDIOS_WKUP_IRQn)

__DEF_GET_IRQ(MDMA, MDMA_IRQn)

__DEF_GET_IRQ(OCTOSPI1, OCTOSPI1_IRQn)

__DEF_GET_IRQ(OCTOSPI2, OCTOSPI2_IRQn)

__DEF_GET_IRQ(OTFDEC1, OTFDEC1_IRQn)

__DEF_GET_IRQ(OTFDEC2, OTFDEC2_IRQn)

__DEF_GET_IRQ(USB_OTG_FS, OTG_FS_EP1_IN_IRQn)

__DEF_GET_IRQ(USB_OTG_FS, OTG_FS_EP1_OUT_IRQn)

__DEF_GET_IRQ(USB_OTG_FS, OTG_FS_IRQn)

__DEF_GET_IRQ(USB_OTG_FS, OTG_FS_WKUP_IRQn)

__DEF_GET_IRQ(USB_OTG_HS, OTG_HS_EP1_IN_IRQn)

__DEF_GET_IRQ(USB_OTG_HS, OTG_HS_EP1_OUT_IRQn)

__DEF_GET_IRQ(USB_OTG_HS, OTG_HS_IRQn)

__DEF_GET_IRQ(USB_OTG_HS, OTG_HS_WKUP_IRQn)

__DEF_GET_IRQ(USB_OTG_HS, OTG_IRQn)

__DEF_GET_IRQ(PKA, PKA_IRQn)

__DEF_GET_IRQ(PWR, PVD_AVD_IRQn)

__DEF_GET_IRQ(QUADSPI, QUADSPI_IRQn)
__DEF_GET_IRQ(QUADSPI1, QUADSPI_IRQn)

__DEF_GET_IRQ(RCC, RCC_CRS_IRQn)

__DEF_GET_IRQ(RCC, RCC_IRQn)

__DEF_GET_IRQ(RCC, RCC_S_IRQn)

__DEF_GET_IRQ(RCC, RCC_WAKEUP_IRQn)

__DEF_GET_IRQ(RNG, RNG_IRQn)

__DEF_GET_IRQ(LPUART1, RNG_LPUART1_IRQn)
__DEF_GET_IRQ(RNG, RNG_LPUART1_IRQn)

__DEF_GET_IRQ(RNG1, RNG1_IRQn)

__DEF_GET_IRQ(RNG2, RNG2_IRQn)

__DEF_GET_IRQ(RTC, RTC_Alarm_IRQn)

__DEF_GET_IRQ(RTC, RTC_IRQn)

__DEF_GET_IRQ(RTC, RTC_S_IRQn)

__DEF_GET_IRQ(RTC, RTC_TAMP_IRQn)

__DEF_GET_IRQ(RTC, RTC_TAMP_LSECSS_IRQn)

__DEF_GET_IRQ(RTC, RTC_TAMP_STAMP_CSS_LSE_IRQn)

__DEF_GET_IRQ(RTC, RTC_TIMESTAMP_IRQn)

__DEF_GET_IRQ(RTC, RTC_WKUP_ALARM_IRQn)

__DEF_GET_IRQ(RTC, RTC_WKUP_IRQn)

__DEF_GET_IRQ(SAI1, SAI1_IRQn)

__DEF_GET_IRQ(SAI2, SAI2_IRQn)

__DEF_GET_IRQ(SAI3, SAI3_IRQn)

__DEF_GET_IRQ(SAI4, SAI4_IRQn)

__DEF_GET_IRQ(SDADC1, SDADC1_IRQn)

__DEF_GET_IRQ(SDADC2, SDADC2_IRQn)

__DEF_GET_IRQ(SDADC3, SDADC3_IRQn)

__DEF_GET_IRQ(SDIO, SDIO_IRQn)

__DEF_GET_IRQ(SDMMC1, SDMMC1_IRQn)

__DEF_GET_IRQ(SDMMC2, SDMMC2_IRQn)

__DEF_GET_IRQ(SDMMC3, SDMMC3_IRQn)

__DEF_GET_IRQ(SPDIFRX, SPDIF_RX_IRQn)
__DEF_GET_IRQ(SPDIFRX1, SPDIF_RX_IRQn)

__DEF_GET_IRQ(I2S1, SPI1_IRQn)
__DEF_GET_IRQ(SPI1, SPI1_IRQn)

__DEF_GET_IRQ(I2S2, SPI2_IRQn)
__DEF_GET_IRQ(SPI2, SPI2_IRQn)

__DEF_GET_IRQ(I2S3, SPI3_IRQn)
__DEF_GET_IRQ(SPI3, SPI3_IRQn)

__DEF_GET_IRQ(I2S4, SPI4_IRQn)
__DEF_GET_IRQ(SPI4, SPI4_IRQn)

__DEF_GET_IRQ(I2S5, SPI5_IRQn)
__DEF_GET_IRQ(SPI5, SPI5_IRQn)

__DEF_GET_IRQ(I2S6, SPI6_IRQn)
__DEF_GET_IRQ(SPI6, SPI6_IRQn)

__DEF_GET_IRQ(SWPMI1, SWPMI1_IRQn)

__DEF_GET_IRQ(RTC, TAMPER_IRQn)

__DEF_GET_IRQ(RTC, TAMPER_STAMP_IRQn)

__DEF_GET_IRQ(TAMP, TAMP_IRQn)

__DEF_GET_IRQ(RTC, TAMP_STAMP_IRQn)

__DEF_GET_IRQ(RTC, TAMP_STAMP_LSECSS_IRQn)

__DEF_GET_IRQ(TAMP, TAMP_S_IRQn)

__DEF_GET_IRQ(TEMPSENS, TEMP_IRQn)

__DEF_GET_IRQ(TIM9, TIM1_BRK_TIM9_IRQn)

__DEF_GET_IRQ(TIM15, TIM1_BRK_TIM15_IRQn)

__DEF_GET_IRQ(TIM1, TIM1_BRK_UP_TRG_COM_IRQn)

__DEF_GET_IRQ(TIM11, TIM1_TRG_COM_TIM11_IRQn)

__DEF_GET_IRQ(TIM17, TIM1_TRG_COM_TIM17_IRQn)

__DEF_GET_IRQ(TIM1, TIM1_UP_IRQn)

__DEF_GET_IRQ(TIM1, TIM1_UP_TIM10_IRQn)
__DEF_GET_IRQ(TIM10, TIM1_UP_TIM10_IRQn)

__DEF_GET_IRQ(TIM1, TIM1_UP_TIM16_IRQn)
__DEF_GET_IRQ(TIM16, TIM1_UP_TIM16_IRQn)

__DEF_GET_IRQ(TIM2, TIM2_IRQn)

__DEF_GET_IRQ(TIM3, TIM3_IRQn)

__DEF_GET_IRQ(TIM4, TIM4_IRQn)

__DEF_GET_IRQ(TIM5, TIM5_IRQn)

__DEF_GET_IRQ(DAC, TIM6_DAC_IRQn)
__DEF_GET_IRQ(DAC1, TIM6_DAC_IRQn)
__DEF_GET_IRQ(DAC3, TIM6_DAC_IRQn)
__DEF_GET_IRQ(TIM6, TIM6_DAC_IRQn)

__DEF_GET_IRQ(DAC1, TIM6_DAC_LPTIM1_IRQn)
__DEF_GET_IRQ(LPTIM1, TIM6_DAC_LPTIM1_IRQn)
__DEF_GET_IRQ(TIM6, TIM6_DAC_LPTIM1_IRQn)

__DEF_GET_IRQ(DAC1, TIM6_DAC1_IRQn)
__DEF_GET_IRQ(TIM6, TIM6_DAC1_IRQn)

__DEF_GET_IRQ(TIM6, TIM6_IRQn)

__DEF_GET_IRQ(DAC2, TIM7_DAC_IRQn)
__DEF_GET_IRQ(DAC4, TIM7_DAC_IRQn)
__DEF_GET_IRQ(TIM7, TIM7_DAC_IRQn)

__DEF_GET_IRQ(DAC2, TIM7_DAC2_IRQn)
__DEF_GET_IRQ(TIM7, TIM7_DAC2_IRQn)

__DEF_GET_IRQ(TIM7, TIM7_IRQn)

__DEF_GET_IRQ(LPTIM2, TIM7_LPTIM2_IRQn)
__DEF_GET_IRQ(TIM7, TIM7_LPTIM2_IRQn)

__DEF_GET_IRQ(TIM8, TIM8_BRK_IRQn)

__DEF_GET_IRQ(TIM8, TIM8_BRK_TIM12_IRQn)
__DEF_GET_IRQ(TIM12, TIM8_BRK_TIM12_IRQn)

__DEF_GET_IRQ(TIM8, TIM8_CC_IRQn)

__DEF_GET_IRQ(TIM8, TIM8_TRG_COM_IRQn)

__DEF_GET_IRQ(TIM8, TIM8_TRG_COM_TIM14_IRQn)
__DEF_GET_IRQ(TIM14, TIM8_TRG_COM_TIM14_IRQn)

__DEF_GET_IRQ(TIM8, TIM8_UP_IRQn)

__DEF_GET_IRQ(TIM8, TIM8_UP_TIM13_IRQn)
__DEF_GET_IRQ(TIM13, TIM8_UP_TIM13_IRQn)

__DEF_GET_IRQ(TIM9, TIM9_IRQn)

__DEF_GET_IRQ(TIM10, TIM10_IRQn)

__DEF_GET_IRQ(TIM11, TIM11_IRQn)

__DEF_GET_IRQ(TIM12, TIM12_IRQn)

__DEF_GET_IRQ(TIM13, TIM13_IRQn)

__DEF_GET_IRQ(TIM14, TIM14_IRQn)

__DEF_GET_IRQ(TIM15, TIM15_IRQn)

__DEF_GET_IRQ(TIM16, TIM16_IRQn)

__DEF_GET_IRQ(TIM17, TIM17_IRQn)

__DEF_GET_IRQ(DAC2, TIM18_DAC2_IRQn)
__DEF_GET_IRQ(TIM18, TIM18_DAC2_IRQn)

__DEF_GET_IRQ(TIM19, TIM19_IRQn)

__DEF_GET_IRQ(TIM20, TIM20_BRK_IRQn)

__DEF_GET_IRQ(TIM20, TIM20_CC_IRQn)

__DEF_GET_IRQ(TIM20, TIM20_TRG_COM_IRQn)

__DEF_GET_IRQ(TIM20, TIM20_UP_IRQn)

__DEF_GET_IRQ(TIM21, TIM21_IRQn)

__DEF_GET_IRQ(TIM22, TIM22_IRQn)

__DEF_GET_IRQ(TIM23, TIM23_IRQn)

__DEF_GET_IRQ(TIM24, TIM24_IRQn)

__DEF_GET_IRQ(TSC, TSC_IRQn)

__DEF_GET_IRQ(UART4, UART4_IRQn)

__DEF_GET_IRQ(UART5, UART5_IRQn)

__DEF_GET_IRQ(UART7, UART7_IRQn)

__DEF_GET_IRQ(UART8, UART8_IRQn)

__DEF_GET_IRQ(UART9, UART9_IRQn)

__DEF_GET_IRQ(UART10, UART10_IRQn)

__DEF_GET_IRQ(UCPD1, UCPD1_IRQn)

__DEF_GET_IRQ(UCPD1, UCPD1_2_IRQn)
__DEF_GET_IRQ(UCPD2, UCPD1_2_IRQn)

__DEF_GET_IRQ(USART1, USART1_IRQn)

__DEF_GET_IRQ(USART2, USART2_IRQn)

__DEF_GET_IRQ(USART3, USART3_IRQn)

__DEF_GET_IRQ(USART3, USART3_4_IRQn)
__DEF_GET_IRQ(USART4, USART3_4_IRQn)

__DEF_GET_IRQ(LPUART1, USART3_4_LPUART1_IRQn)
__DEF_GET_IRQ(USART3, USART3_4_LPUART1_IRQn)
__DEF_GET_IRQ(USART4, USART3_4_LPUART1_IRQn)

__DEF_GET_IRQ(USART3, USART3_6_IRQn)
__DEF_GET_IRQ(USART4, USART3_6_IRQn)
__DEF_GET_IRQ(USART5, USART3_6_IRQn)
__DEF_GET_IRQ(USART6, USART3_6_IRQn)

__DEF_GET_IRQ(USART3, USART3_8_IRQn)
__DEF_GET_IRQ(USART4, USART3_8_IRQn)
__DEF_GET_IRQ(USART5, USART3_8_IRQn)
__DEF_GET_IRQ(USART6, USART3_8_IRQn)
__DEF_GET_IRQ(USART7, USART3_8_IRQn)
__DEF_GET_IRQ(USART8, USART3_8_IRQn)

__DEF_GET_IRQ(USART4, USART4_5_IRQn)
__DEF_GET_IRQ(USART5, USART4_5_IRQn)

__DEF_GET_IRQ(USART6, USART6_IRQn)

__DEF_GET_IRQ(USART10, USART10_IRQn)

__DEF_GET_IRQ(USBH_HS2, USBH_EHCI_IRQn)

__DEF_GET_IRQ(USBH_HS1, USBH_OHCI_IRQn)

__DEF_GET_IRQ(USB, USBWakeUp_IRQn)

__DEF_GET_IRQ(USB, USBWakeUp_RMP_IRQn)

__DEF_GET_IRQ(USB, USB_FS_IRQn)

__DEF_GET_IRQ(USB, USB_FS_WKUP_IRQn)

__DEF_GET_IRQ(CAN, USB_HP_CAN_TX_IRQn)
__DEF_GET_IRQ(USB, USB_HP_CAN_TX_IRQn)

__DEF_GET_IRQ(CAN, USB_HP_CAN1_TX_IRQn)
__DEF_GET_IRQ(USB, USB_HP_CAN1_TX_IRQn)

__DEF_GET_IRQ(USB, USB_HP_IRQn)

__DEF_GET_IRQ(USB, USB_IRQn)

__DEF_GET_IRQ(CAN, USB_LP_CAN_RX0_IRQn)
__DEF_GET_IRQ(USB, USB_LP_CAN_RX0_IRQn)

__DEF_GET_IRQ(CAN, USB_LP_CAN1_RX0_IRQn)
__DEF_GET_IRQ(USB, USB_LP_CAN1_RX0_IRQn)

__DEF_GET_IRQ(USB, USB_LP_IRQn)

__DEF_GET_IRQ(PWR, WAKEUP_PIN_IRQn)

__DEF_GET_IRQ(WWDG, WWDG_IRQn)
__DEF_GET_IRQ(WWDG1, WWDG_IRQn)
__DEF_GET_IRQ(WWDG2, WWDG_IRQn)

__DEF_GET_IRQ(WWDG1, WWDG_RST_IRQn)
__DEF_GET_IRQ(WWDG2, WWDG_RST_IRQn)

__DEF_GET_IRQ(WWDG1, WWDG1_IRQn)


/* C++ SFINAE for clearing the right NVIC IRQn */
/**
 * Defines a clearNvicItForXXX() function overload which clears the given IRQn,
 * if such an IRQ exists.
 * 
 * @param[in] IRQn - STM32 HAL IRQ number constant
 */
#define __DEF_CLEAR_NVIC_IRQ(IRQn) \
	template <typename T> \
	static inline void clearNvicIrqFor##IRQn(decltype(T::IRQn) *) { \
		HAL_NVIC_ClearPendingIRQ(T::IRQn); \
		__ISB(); /* Ensure that the IRQ was really cleared at this point. */ \
	} \
	template <typename T> \
	static inline void clearNvicIrqFor##IRQn(...) {}

/**
 * Clears the given pending NVIC interrupt.
 * 
 * @param[in] IRQn - STM32 HAL IRQ number constant
 */
#define clearNvicIrqFor(IRQn) clearNvicIrqFor##IRQn<IRQn_Type>(0)


/* Define functions to clear pending NVIC IRQs if available for the current platform for all IRQs available. */
__DEF_CLEAR_NVIC_IRQ(ADC_IRQn)
__DEF_CLEAR_NVIC_IRQ(ADC1_COMP_IRQn)
__DEF_CLEAR_NVIC_IRQ(ADC1_IRQn)
__DEF_CLEAR_NVIC_IRQ(ADC1_2_IRQn)
__DEF_CLEAR_NVIC_IRQ(ADC2_IRQn)
__DEF_CLEAR_NVIC_IRQ(ADC3_IRQn)
__DEF_CLEAR_NVIC_IRQ(ADC4_IRQn)
__DEF_CLEAR_NVIC_IRQ(ADC5_IRQn)

__DEF_CLEAR_NVIC_IRQ(AES_IRQn)
__DEF_CLEAR_NVIC_IRQ(AES_RNG_IRQn)
__DEF_CLEAR_NVIC_IRQ(AES_RNG_LPUART1_IRQn)
__DEF_CLEAR_NVIC_IRQ(AES1_IRQn)
__DEF_CLEAR_NVIC_IRQ(AES2_IRQn)

__DEF_CLEAR_NVIC_IRQ(BDMA_Channel0_IRQn)
__DEF_CLEAR_NVIC_IRQ(BDMA_Channel1_IRQn)
__DEF_CLEAR_NVIC_IRQ(BDMA_Channel2_IRQn)
__DEF_CLEAR_NVIC_IRQ(BDMA_Channel3_IRQn)
__DEF_CLEAR_NVIC_IRQ(BDMA_Channel4_IRQn)
__DEF_CLEAR_NVIC_IRQ(BDMA_Channel5_IRQn)
__DEF_CLEAR_NVIC_IRQ(BDMA_Channel6_IRQn)
__DEF_CLEAR_NVIC_IRQ(BDMA_Channel7_IRQn)
__DEF_CLEAR_NVIC_IRQ(BDMA1_IRQn)
__DEF_CLEAR_NVIC_IRQ(BDMA2_Channel0_IRQn)
__DEF_CLEAR_NVIC_IRQ(BDMA2_Channel1_IRQn)
__DEF_CLEAR_NVIC_IRQ(BDMA2_Channel2_IRQn)
__DEF_CLEAR_NVIC_IRQ(BDMA2_Channel3_IRQn)
__DEF_CLEAR_NVIC_IRQ(BDMA2_Channel4_IRQn)
__DEF_CLEAR_NVIC_IRQ(BDMA2_Channel5_IRQn)
__DEF_CLEAR_NVIC_IRQ(BDMA2_Channel6_IRQn)
__DEF_CLEAR_NVIC_IRQ(BDMA2_Channel7_IRQn)

__DEF_CLEAR_NVIC_IRQ(BusFault_IRQn)

__DEF_CLEAR_NVIC_IRQ(CAN_RX0_IRQn)
__DEF_CLEAR_NVIC_IRQ(CAN_RX1_IRQn)
__DEF_CLEAR_NVIC_IRQ(CAN_SCE_IRQn)
__DEF_CLEAR_NVIC_IRQ(CAN_TX_IRQn)
__DEF_CLEAR_NVIC_IRQ(CAN1_RX0_IRQn)
__DEF_CLEAR_NVIC_IRQ(CAN1_RX1_IRQn)
__DEF_CLEAR_NVIC_IRQ(CAN1_SCE_IRQn)
__DEF_CLEAR_NVIC_IRQ(CAN1_TX_IRQn)
__DEF_CLEAR_NVIC_IRQ(CAN2_RX0_IRQn)
__DEF_CLEAR_NVIC_IRQ(CAN2_RX1_IRQn)
__DEF_CLEAR_NVIC_IRQ(CAN2_SCE_IRQn)
__DEF_CLEAR_NVIC_IRQ(CAN2_TX_IRQn)
__DEF_CLEAR_NVIC_IRQ(CAN3_RX0_IRQn)
__DEF_CLEAR_NVIC_IRQ(CAN3_RX1_IRQn)
__DEF_CLEAR_NVIC_IRQ(CAN3_SCE_IRQn)
__DEF_CLEAR_NVIC_IRQ(CAN3_TX_IRQn)

__DEF_CLEAR_NVIC_IRQ(CEC_CAN_IRQn)
__DEF_CLEAR_NVIC_IRQ(CEC_IRQn)

__DEF_CLEAR_NVIC_IRQ(CM4_SEV_IRQn)
__DEF_CLEAR_NVIC_IRQ(CM7_SEV_IRQn)

__DEF_CLEAR_NVIC_IRQ(COMP_ACQ_IRQn)
__DEF_CLEAR_NVIC_IRQ(COMP_IRQn)
__DEF_CLEAR_NVIC_IRQ(COMP1_2_IRQn)
__DEF_CLEAR_NVIC_IRQ(COMP1_2_3_IRQn)
__DEF_CLEAR_NVIC_IRQ(COMP2_IRQn)
__DEF_CLEAR_NVIC_IRQ(COMP4_IRQn)
__DEF_CLEAR_NVIC_IRQ(COMP4_5_6_IRQn)
__DEF_CLEAR_NVIC_IRQ(COMP4_6_IRQn)
__DEF_CLEAR_NVIC_IRQ(COMP7_IRQn)

__DEF_CLEAR_NVIC_IRQ(CORDIC_IRQn)

__DEF_CLEAR_NVIC_IRQ(CRS_IRQn)

__DEF_CLEAR_NVIC_IRQ(CRYP_IRQn)
__DEF_CLEAR_NVIC_IRQ(CRYP1_IRQn)
__DEF_CLEAR_NVIC_IRQ(CRYP2_IRQn)

__DEF_CLEAR_NVIC_IRQ(C2SEV_PWR_C2H_IRQn)

__DEF_CLEAR_NVIC_IRQ(DAC_IRQn)
__DEF_CLEAR_NVIC_IRQ(DAC2_IRQn)

__DEF_CLEAR_NVIC_IRQ(DCMI_IRQn)
__DEF_CLEAR_NVIC_IRQ(DCMI_PSSI_IRQn)

__DEF_CLEAR_NVIC_IRQ(DFSDM1_FLT0_IRQn)
__DEF_CLEAR_NVIC_IRQ(DFSDM1_FLT1_IRQn)
__DEF_CLEAR_NVIC_IRQ(DFSDM1_FLT2_IRQn)
__DEF_CLEAR_NVIC_IRQ(DFSDM1_FLT3_IRQn)
__DEF_CLEAR_NVIC_IRQ(DFSDM1_FLT4_IRQn)
__DEF_CLEAR_NVIC_IRQ(DFSDM1_FLT5_IRQn)
__DEF_CLEAR_NVIC_IRQ(DFSDM1_FLT6_IRQn)
__DEF_CLEAR_NVIC_IRQ(DFSDM1_FLT7_IRQn)
__DEF_CLEAR_NVIC_IRQ(DFSDM2_FLT0_IRQn)
__DEF_CLEAR_NVIC_IRQ(DFSDM2_FLT1_IRQn)
__DEF_CLEAR_NVIC_IRQ(DFSDM2_FLT2_IRQn)
__DEF_CLEAR_NVIC_IRQ(DFSDM2_FLT3_IRQn)
__DEF_CLEAR_NVIC_IRQ(DFSDM2_IRQn)

__DEF_CLEAR_NVIC_IRQ(DMAMUX_OVR_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMAMUX1_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMAMUX1_OVR_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMAMUX1_S_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMAMUX2_OVR_IRQn)

__DEF_CLEAR_NVIC_IRQ(DMA1_Channel1_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA1_Channel2_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA1_Channel2_3_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA1_Channel3_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA1_Channel4_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA1_Channel4_5_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA1_Channel4_5_6_7_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA1_Channel5_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA1_Channel6_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA1_Channel7_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA1_Channel8_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA1_Ch1_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA1_Ch2_3_DMA2_Ch1_2_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA1_Ch4_5_DMAMUX1_OVR_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA1_Ch4_7_DMAMUX1_OVR_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA1_Ch4_7_DMA2_Ch3_5_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA1_Stream0_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA1_Stream1_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA1_Stream2_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA1_Stream3_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA1_Stream4_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA1_Stream5_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA1_Stream6_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA1_Stream7_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA2D_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA2_Channel1_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA2_Channel2_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA2_Channel3_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA2_Channel4_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA2_Channel4_5_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA2_Channel5_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA2_Channel6_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA2_Channel7_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA2_Channel8_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA2_Stream0_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA2_Stream1_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA2_Stream2_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA2_Stream3_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA2_Stream4_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA2_Stream5_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA2_Stream6_IRQn)
__DEF_CLEAR_NVIC_IRQ(DMA2_Stream7_IRQn)

__DEF_CLEAR_NVIC_IRQ(DSI_IRQn)

__DEF_CLEAR_NVIC_IRQ(DTS_IRQn)

__DEF_CLEAR_NVIC_IRQ(DebugMonitor_IRQn)

__DEF_CLEAR_NVIC_IRQ(ECC_IRQn)

__DEF_CLEAR_NVIC_IRQ(ETH_IRQn)
__DEF_CLEAR_NVIC_IRQ(ETH_WKUP_IRQn)
__DEF_CLEAR_NVIC_IRQ(ETH1_IRQn)
__DEF_CLEAR_NVIC_IRQ(ETH1_LPI_IRQn)
__DEF_CLEAR_NVIC_IRQ(ETH1_WKUP_IRQn)

__DEF_CLEAR_NVIC_IRQ(EXTI0_IRQn)
__DEF_CLEAR_NVIC_IRQ(EXTI0_1_IRQn)
__DEF_CLEAR_NVIC_IRQ(EXTI1_IRQn)
__DEF_CLEAR_NVIC_IRQ(EXTI2_IRQn)
__DEF_CLEAR_NVIC_IRQ(EXTI2_TSC_IRQn)
__DEF_CLEAR_NVIC_IRQ(EXTI2_3_IRQn)
__DEF_CLEAR_NVIC_IRQ(EXTI3_IRQn)
__DEF_CLEAR_NVIC_IRQ(EXTI4_IRQn)
__DEF_CLEAR_NVIC_IRQ(EXTI4_15_IRQn)
__DEF_CLEAR_NVIC_IRQ(EXTI5_IRQn)
__DEF_CLEAR_NVIC_IRQ(EXTI6_IRQn)
__DEF_CLEAR_NVIC_IRQ(EXTI7_IRQn)
__DEF_CLEAR_NVIC_IRQ(EXTI8_IRQn)
__DEF_CLEAR_NVIC_IRQ(EXTI9_IRQn)
__DEF_CLEAR_NVIC_IRQ(EXTI9_5_IRQn)
__DEF_CLEAR_NVIC_IRQ(EXTI10_IRQn)
__DEF_CLEAR_NVIC_IRQ(EXTI11_IRQn)
__DEF_CLEAR_NVIC_IRQ(EXTI12_IRQn)
__DEF_CLEAR_NVIC_IRQ(EXTI13_IRQn)
__DEF_CLEAR_NVIC_IRQ(EXTI14_IRQn)
__DEF_CLEAR_NVIC_IRQ(EXTI15_IRQn)
__DEF_CLEAR_NVIC_IRQ(EXTI15_10_IRQn)

__DEF_CLEAR_NVIC_IRQ(FDCAN_CAL_IRQn)
__DEF_CLEAR_NVIC_IRQ(FDCAN1_IT0_IRQn)
__DEF_CLEAR_NVIC_IRQ(FDCAN1_IT1_IRQn)
__DEF_CLEAR_NVIC_IRQ(FDCAN2_IT0_IRQn)
__DEF_CLEAR_NVIC_IRQ(FDCAN2_IT1_IRQn)
__DEF_CLEAR_NVIC_IRQ(FDCAN3_IT0_IRQn)
__DEF_CLEAR_NVIC_IRQ(FDCAN3_IT1_IRQn)

__DEF_CLEAR_NVIC_IRQ(FLASH_IRQn)
__DEF_CLEAR_NVIC_IRQ(FLASH_S_IRQn)

__DEF_CLEAR_NVIC_IRQ(FMAC_IRQn)

__DEF_CLEAR_NVIC_IRQ(FMC_IRQn)

__DEF_CLEAR_NVIC_IRQ(FMPI2C1_ER_IRQn)
__DEF_CLEAR_NVIC_IRQ(FMPI2C1_EV_IRQn)

__DEF_CLEAR_NVIC_IRQ(FPU_IRQn)

__DEF_CLEAR_NVIC_IRQ(FSMC_IRQn)

__DEF_CLEAR_NVIC_IRQ(GFXMMU_IRQn)

__DEF_CLEAR_NVIC_IRQ(GPU_IRQn)

__DEF_CLEAR_NVIC_IRQ(GTZC_IRQn)

__DEF_CLEAR_NVIC_IRQ(HASH_CRS_IRQn)
__DEF_CLEAR_NVIC_IRQ(HASH_IRQn)
__DEF_CLEAR_NVIC_IRQ(HASH_RNG_IRQn)
__DEF_CLEAR_NVIC_IRQ(HASH1_IRQn)
__DEF_CLEAR_NVIC_IRQ(HASH2_IRQn)

__DEF_CLEAR_NVIC_IRQ(HOLD_CORE_IRQn)

__DEF_CLEAR_NVIC_IRQ(HRTIM1_FLT_IRQn)
__DEF_CLEAR_NVIC_IRQ(HRTIM1_Master_IRQn)
__DEF_CLEAR_NVIC_IRQ(HRTIM1_TIMA_IRQn)
__DEF_CLEAR_NVIC_IRQ(HRTIM1_TIMB_IRQn)
__DEF_CLEAR_NVIC_IRQ(HRTIM1_TIMC_IRQn)
__DEF_CLEAR_NVIC_IRQ(HRTIM1_TIMD_IRQn)
__DEF_CLEAR_NVIC_IRQ(HRTIM1_TIME_IRQn)
__DEF_CLEAR_NVIC_IRQ(HRTIM1_TIMF_IRQn)

__DEF_CLEAR_NVIC_IRQ(HSEM_IRQn)
__DEF_CLEAR_NVIC_IRQ(HSEM_IT2_IRQn)
__DEF_CLEAR_NVIC_IRQ(HSEM1_IRQn)
__DEF_CLEAR_NVIC_IRQ(HSEM2_IRQn)

__DEF_CLEAR_NVIC_IRQ(HardFault_IRQn)

__DEF_CLEAR_NVIC_IRQ(ICACHE_IRQn)

__DEF_CLEAR_NVIC_IRQ(IPCC_C1_RX_IRQn)
__DEF_CLEAR_NVIC_IRQ(IPCC_C1_TX_IRQn)
__DEF_CLEAR_NVIC_IRQ(IPCC_RX0_IRQn)
__DEF_CLEAR_NVIC_IRQ(IPCC_RX1_IRQn)
__DEF_CLEAR_NVIC_IRQ(IPCC_TX0_IRQn)
__DEF_CLEAR_NVIC_IRQ(IPCC_TX1_IRQn)

__DEF_CLEAR_NVIC_IRQ(I2C1_ER_IRQn)
__DEF_CLEAR_NVIC_IRQ(I2C1_EV_IRQn)
__DEF_CLEAR_NVIC_IRQ(I2C1_IRQn)
__DEF_CLEAR_NVIC_IRQ(I2C2_ER_IRQn)
__DEF_CLEAR_NVIC_IRQ(I2C2_EV_IRQn)
__DEF_CLEAR_NVIC_IRQ(I2C2_IRQn)
__DEF_CLEAR_NVIC_IRQ(I2C3_ER_IRQn)
__DEF_CLEAR_NVIC_IRQ(I2C3_EV_IRQn)
__DEF_CLEAR_NVIC_IRQ(I2C3_IRQn)
__DEF_CLEAR_NVIC_IRQ(I2C4_ER_IRQn)
__DEF_CLEAR_NVIC_IRQ(I2C4_EV_IRQn)
__DEF_CLEAR_NVIC_IRQ(I2C5_ER_IRQn)
__DEF_CLEAR_NVIC_IRQ(I2C5_EV_IRQn)
__DEF_CLEAR_NVIC_IRQ(I2C6_ER_IRQn)
__DEF_CLEAR_NVIC_IRQ(I2C6_EV_IRQn)

__DEF_CLEAR_NVIC_IRQ(JPEG_IRQn)

__DEF_CLEAR_NVIC_IRQ(LCD_IRQn)

__DEF_CLEAR_NVIC_IRQ(LPTIM1_IRQn)
__DEF_CLEAR_NVIC_IRQ(LPTIM2_IRQn)
__DEF_CLEAR_NVIC_IRQ(LPTIM3_IRQn)
__DEF_CLEAR_NVIC_IRQ(LPTIM4_IRQn)
__DEF_CLEAR_NVIC_IRQ(LPTIM5_IRQn)

__DEF_CLEAR_NVIC_IRQ(LPUART1_IRQn)

__DEF_CLEAR_NVIC_IRQ(LTDC_ER_IRQn)
__DEF_CLEAR_NVIC_IRQ(LTDC_IRQn)

__DEF_CLEAR_NVIC_IRQ(MDIOS_IRQn)
__DEF_CLEAR_NVIC_IRQ(MDIOS_WKUP_IRQn)

__DEF_CLEAR_NVIC_IRQ(MDMA_IRQn)

__DEF_CLEAR_NVIC_IRQ(MPU_SEV_IRQn)

__DEF_CLEAR_NVIC_IRQ(MemoryManagement_IRQn)

__DEF_CLEAR_NVIC_IRQ(NonMaskableInt_IRQn)

__DEF_CLEAR_NVIC_IRQ(OCTOSPI1_IRQn)
__DEF_CLEAR_NVIC_IRQ(OCTOSPI2_IRQn)

__DEF_CLEAR_NVIC_IRQ(OTFDEC1_IRQn)
__DEF_CLEAR_NVIC_IRQ(OTFDEC2_IRQn)

__DEF_CLEAR_NVIC_IRQ(OTG_FS_EP1_IN_IRQn)
__DEF_CLEAR_NVIC_IRQ(OTG_FS_EP1_OUT_IRQn)
__DEF_CLEAR_NVIC_IRQ(OTG_FS_IRQn)
__DEF_CLEAR_NVIC_IRQ(OTG_FS_WKUP_IRQn)
__DEF_CLEAR_NVIC_IRQ(OTG_HS_EP1_IN_IRQn)
__DEF_CLEAR_NVIC_IRQ(OTG_HS_EP1_OUT_IRQn)
__DEF_CLEAR_NVIC_IRQ(OTG_HS_IRQn)
__DEF_CLEAR_NVIC_IRQ(OTG_HS_WKUP_IRQn)
__DEF_CLEAR_NVIC_IRQ(OTG_IRQn)

__DEF_CLEAR_NVIC_IRQ(PKA_IRQn)

__DEF_CLEAR_NVIC_IRQ(PVD_AVD_IRQn)
__DEF_CLEAR_NVIC_IRQ(PVD_IRQn)
__DEF_CLEAR_NVIC_IRQ(PVD_PVM_IRQn)
__DEF_CLEAR_NVIC_IRQ(PVD_VDDIO2_IRQn)

__DEF_CLEAR_NVIC_IRQ(PWR_SOTF_BLEACT_802ACT_RFPHASE_IRQn)

__DEF_CLEAR_NVIC_IRQ(PendSV_IRQn)

__DEF_CLEAR_NVIC_IRQ(QUADSPI_IRQn)

__DEF_CLEAR_NVIC_IRQ(RCC_CRS_IRQn)
__DEF_CLEAR_NVIC_IRQ(RCC_IRQn)
__DEF_CLEAR_NVIC_IRQ(RCC_S_IRQn)
__DEF_CLEAR_NVIC_IRQ(RCC_WAKEUP_IRQn)

__DEF_CLEAR_NVIC_IRQ(RNG_IRQn)
__DEF_CLEAR_NVIC_IRQ(RNG_LPUART1_IRQn)
__DEF_CLEAR_NVIC_IRQ(RNG1_IRQn)
__DEF_CLEAR_NVIC_IRQ(RNG2_IRQn)

__DEF_CLEAR_NVIC_IRQ(RTC_Alarm_IRQn)
__DEF_CLEAR_NVIC_IRQ(RTC_IRQn)
__DEF_CLEAR_NVIC_IRQ(RTC_S_IRQn)
__DEF_CLEAR_NVIC_IRQ(RTC_TAMP_IRQn)
__DEF_CLEAR_NVIC_IRQ(RTC_TAMP_LSECSS_IRQn)
__DEF_CLEAR_NVIC_IRQ(RTC_TAMP_STAMP_CSS_LSE_IRQn)
__DEF_CLEAR_NVIC_IRQ(RTC_TIMESTAMP_IRQn)
__DEF_CLEAR_NVIC_IRQ(RTC_WKUP_ALARM_IRQn)
__DEF_CLEAR_NVIC_IRQ(RTC_WKUP_IRQn)

__DEF_CLEAR_NVIC_IRQ(SAI1_IRQn)
__DEF_CLEAR_NVIC_IRQ(SAI2_IRQn)
__DEF_CLEAR_NVIC_IRQ(SAI3_IRQn)
__DEF_CLEAR_NVIC_IRQ(SAI4_IRQn)

__DEF_CLEAR_NVIC_IRQ(SDADC1_IRQn)
__DEF_CLEAR_NVIC_IRQ(SDADC2_IRQn)
__DEF_CLEAR_NVIC_IRQ(SDADC3_IRQn)

__DEF_CLEAR_NVIC_IRQ(SDIO_IRQn)

__DEF_CLEAR_NVIC_IRQ(SDMMC1_IRQn)
__DEF_CLEAR_NVIC_IRQ(SDMMC2_IRQn)
__DEF_CLEAR_NVIC_IRQ(SDMMC3_IRQn)

__DEF_CLEAR_NVIC_IRQ(SPDIF_RX_IRQn)

__DEF_CLEAR_NVIC_IRQ(SPI1_IRQn)
__DEF_CLEAR_NVIC_IRQ(SPI2_IRQn)
__DEF_CLEAR_NVIC_IRQ(SPI3_IRQn)
__DEF_CLEAR_NVIC_IRQ(SPI4_IRQn)
__DEF_CLEAR_NVIC_IRQ(SPI5_IRQn)
__DEF_CLEAR_NVIC_IRQ(SPI6_IRQn)

__DEF_CLEAR_NVIC_IRQ(SVC_IRQn)

__DEF_CLEAR_NVIC_IRQ(SVCall_IRQn)

__DEF_CLEAR_NVIC_IRQ(SWPMI1_IRQn)

__DEF_CLEAR_NVIC_IRQ(SecureFault_IRQn)

__DEF_CLEAR_NVIC_IRQ(SysTick_IRQn)

__DEF_CLEAR_NVIC_IRQ(TAMPER_IRQn)
__DEF_CLEAR_NVIC_IRQ(TAMPER_STAMP_IRQn)

__DEF_CLEAR_NVIC_IRQ(TAMP_IRQn)
__DEF_CLEAR_NVIC_IRQ(TAMP_STAMP_IRQn)
__DEF_CLEAR_NVIC_IRQ(TAMP_STAMP_LSECSS_IRQn)
__DEF_CLEAR_NVIC_IRQ(TAMP_S_IRQn)

__DEF_CLEAR_NVIC_IRQ(TEMP_IRQn)

__DEF_CLEAR_NVIC_IRQ(TIM1_BRK_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM1_BRK_TIM9_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM1_BRK_TIM15_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM1_BRK_UP_TRG_COM_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM1_CC_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM1_TRG_COM_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM1_TRG_COM_TIM11_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM1_TRG_COM_TIM17_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM1_UP_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM1_UP_TIM10_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM1_UP_TIM16_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM2_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM3_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM4_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM5_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM6_DAC_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM6_DAC_LPTIM1_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM6_DAC1_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM6_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM7_DAC_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM7_DAC2_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM7_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM7_LPTIM2_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM8_BRK_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM8_BRK_TIM12_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM8_CC_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM8_TRG_COM_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM8_TRG_COM_TIM14_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM8_UP_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM8_UP_TIM13_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM9_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM10_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM11_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM12_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM13_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM14_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM15_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM16_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM17_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM18_DAC2_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM19_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM20_BRK_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM20_CC_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM20_TRG_COM_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM20_UP_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM21_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM22_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM23_IRQn)
__DEF_CLEAR_NVIC_IRQ(TIM24_IRQn)

__DEF_CLEAR_NVIC_IRQ(TSC_IRQn)

__DEF_CLEAR_NVIC_IRQ(UART4_IRQn)
__DEF_CLEAR_NVIC_IRQ(UART5_IRQn)
__DEF_CLEAR_NVIC_IRQ(UART7_IRQn)
__DEF_CLEAR_NVIC_IRQ(UART8_IRQn)
__DEF_CLEAR_NVIC_IRQ(UART9_IRQn)
__DEF_CLEAR_NVIC_IRQ(UART10_IRQn)

__DEF_CLEAR_NVIC_IRQ(UCPD1_IRQn)
__DEF_CLEAR_NVIC_IRQ(UCPD1_2_IRQn)

__DEF_CLEAR_NVIC_IRQ(USART1_IRQn)
__DEF_CLEAR_NVIC_IRQ(USART2_IRQn)
__DEF_CLEAR_NVIC_IRQ(USART3_IRQn)
__DEF_CLEAR_NVIC_IRQ(USART3_4_IRQn)
__DEF_CLEAR_NVIC_IRQ(USART3_4_LPUART1_IRQn)
__DEF_CLEAR_NVIC_IRQ(USART3_6_IRQn)
__DEF_CLEAR_NVIC_IRQ(USART3_8_IRQn)
__DEF_CLEAR_NVIC_IRQ(USART4_5_IRQn)
__DEF_CLEAR_NVIC_IRQ(USART6_IRQn)
__DEF_CLEAR_NVIC_IRQ(USART10_IRQn)

__DEF_CLEAR_NVIC_IRQ(USBH_EHCI_IRQn)
__DEF_CLEAR_NVIC_IRQ(USBH_OHCI_IRQn)

__DEF_CLEAR_NVIC_IRQ(USBWakeUp_IRQn)
__DEF_CLEAR_NVIC_IRQ(USBWakeUp_RMP_IRQn)

__DEF_CLEAR_NVIC_IRQ(USB_FS_IRQn)
__DEF_CLEAR_NVIC_IRQ(USB_FS_WKUP_IRQn)
__DEF_CLEAR_NVIC_IRQ(USB_HP_CAN_TX_IRQn)
__DEF_CLEAR_NVIC_IRQ(USB_HP_CAN1_TX_IRQn)
__DEF_CLEAR_NVIC_IRQ(USB_HP_IRQn)
__DEF_CLEAR_NVIC_IRQ(USB_IRQn)
__DEF_CLEAR_NVIC_IRQ(USB_LP_CAN_RX0_IRQn)
__DEF_CLEAR_NVIC_IRQ(USB_LP_CAN1_RX0_IRQn)
__DEF_CLEAR_NVIC_IRQ(USB_LP_IRQn)

__DEF_CLEAR_NVIC_IRQ(UsageFault_IRQn)

__DEF_CLEAR_NVIC_IRQ(VDDIO2_IRQn)

__DEF_CLEAR_NVIC_IRQ(WAKEUP_PIN_IRQn)

__DEF_CLEAR_NVIC_IRQ(WWDG_IRQn)
__DEF_CLEAR_NVIC_IRQ(WWDG_RST_IRQn)
__DEF_CLEAR_NVIC_IRQ(WWDG1_IRQn)

__DEF_CLEAR_NVIC_IRQ(nCTIIRQ1_IRQn)
__DEF_CLEAR_NVIC_IRQ(nCTIIRQ2_IRQn)


extern "C" {
/* Remapped IRQ routines. One per STM32 HAL instance. These may be overwritten by STM32CubeDuino handlers or the user. */
extern void STM32CubeDuinoIrqHandlerForADC(void);
extern void STM32CubeDuinoIrqHandlerForADC1(void);
extern void STM32CubeDuinoIrqHandlerForADC2(void);
extern void STM32CubeDuinoIrqHandlerForADC3(void);
extern void STM32CubeDuinoIrqHandlerForADC4(void);
extern void STM32CubeDuinoIrqHandlerForADC5(void);
extern void STM32CubeDuinoIrqHandlerForAES(void);
extern void STM32CubeDuinoIrqHandlerForAES1(void);
extern void STM32CubeDuinoIrqHandlerForAES2(void);
extern void STM32CubeDuinoIrqHandlerForBDMA_CH0(void);
extern void STM32CubeDuinoIrqHandlerForBDMA_CH1(void);
extern void STM32CubeDuinoIrqHandlerForBDMA_CH2(void);
extern void STM32CubeDuinoIrqHandlerForBDMA_CH3(void);
extern void STM32CubeDuinoIrqHandlerForBDMA_CH4(void);
extern void STM32CubeDuinoIrqHandlerForBDMA_CH5(void);
extern void STM32CubeDuinoIrqHandlerForBDMA_CH6(void);
extern void STM32CubeDuinoIrqHandlerForBDMA_CH7(void);
extern void STM32CubeDuinoIrqHandlerForBDMA(void);
extern void STM32CubeDuinoIrqHandlerForBDMA1_CH0(void);
extern void STM32CubeDuinoIrqHandlerForBDMA1_CH1(void);
extern void STM32CubeDuinoIrqHandlerForBDMA1_CH2(void);
extern void STM32CubeDuinoIrqHandlerForBDMA1_CH3(void);
extern void STM32CubeDuinoIrqHandlerForBDMA1_CH4(void);
extern void STM32CubeDuinoIrqHandlerForBDMA1_CH5(void);
extern void STM32CubeDuinoIrqHandlerForBDMA1_CH6(void);
extern void STM32CubeDuinoIrqHandlerForBDMA1_CH7(void);
extern void STM32CubeDuinoIrqHandlerForBDMA2_CH0(void);
extern void STM32CubeDuinoIrqHandlerForBDMA2_CH1(void);
extern void STM32CubeDuinoIrqHandlerForBDMA2_CH2(void);
extern void STM32CubeDuinoIrqHandlerForBDMA2_CH3(void);
extern void STM32CubeDuinoIrqHandlerForBDMA2_CH4(void);
extern void STM32CubeDuinoIrqHandlerForBDMA2_CH5(void);
extern void STM32CubeDuinoIrqHandlerForBDMA2_CH6(void);
extern void STM32CubeDuinoIrqHandlerForBDMA2_CH7(void);
extern void STM32CubeDuinoIrqHandlerForBDMA2(void);
extern void STM32CubeDuinoIrqHandlerForCAN(void);
extern void STM32CubeDuinoIrqHandlerForCAN1(void);
extern void STM32CubeDuinoIrqHandlerForCAN2(void);
extern void STM32CubeDuinoIrqHandlerForCAN3(void);
extern void STM32CubeDuinoIrqHandlerForCEC(void);
extern void STM32CubeDuinoIrqHandlerForCLK_CTRL(void);
extern void STM32CubeDuinoIrqHandlerForCOMP1(void);
extern void STM32CubeDuinoIrqHandlerForCOMP2(void);
extern void STM32CubeDuinoIrqHandlerForCOMP3(void);
extern void STM32CubeDuinoIrqHandlerForCOMP4(void);
extern void STM32CubeDuinoIrqHandlerForCOMP5(void);
extern void STM32CubeDuinoIrqHandlerForCOMP6(void);
extern void STM32CubeDuinoIrqHandlerForCOMP7(void);
extern void STM32CubeDuinoIrqHandlerForCORDIC(void);
extern void STM32CubeDuinoIrqHandlerForCRS(void);
extern void STM32CubeDuinoIrqHandlerForCRYP(void);
extern void STM32CubeDuinoIrqHandlerForCRYP1(void);
extern void STM32CubeDuinoIrqHandlerForCRYP2(void);
extern void STM32CubeDuinoIrqHandlerForDAC(void);
extern void STM32CubeDuinoIrqHandlerForDAC1(void);
extern void STM32CubeDuinoIrqHandlerForDAC2(void);
extern void STM32CubeDuinoIrqHandlerForDAC3(void);
extern void STM32CubeDuinoIrqHandlerForDAC4(void);
extern void STM32CubeDuinoIrqHandlerForDCMI(void);
extern void STM32CubeDuinoIrqHandlerForDFSDM1(void);
extern void STM32CubeDuinoIrqHandlerForDFSDM2(void);
extern void STM32CubeDuinoIrqHandlerForDMA(void);
extern void STM32CubeDuinoIrqHandlerForDMA1_CH0(void);
extern void STM32CubeDuinoIrqHandlerForDMA1_CH1(void);
extern void STM32CubeDuinoIrqHandlerForDMA1_CH2(void);
extern void STM32CubeDuinoIrqHandlerForDMA1_CH3(void);
extern void STM32CubeDuinoIrqHandlerForDMA1_CH4(void);
extern void STM32CubeDuinoIrqHandlerForDMA1_CH5(void);
extern void STM32CubeDuinoIrqHandlerForDMA1_CH6(void);
extern void STM32CubeDuinoIrqHandlerForDMA1_CH7(void);
extern void STM32CubeDuinoIrqHandlerForDMA1_CH8(void);
extern void STM32CubeDuinoIrqHandlerForDMA2D(void);
extern void STM32CubeDuinoIrqHandlerForDMA2_CH0(void);
extern void STM32CubeDuinoIrqHandlerForDMA2_CH1(void);
extern void STM32CubeDuinoIrqHandlerForDMA2_CH2(void);
extern void STM32CubeDuinoIrqHandlerForDMA2_CH3(void);
extern void STM32CubeDuinoIrqHandlerForDMA2_CH4(void);
extern void STM32CubeDuinoIrqHandlerForDMA2_CH5(void);
extern void STM32CubeDuinoIrqHandlerForDMA2_CH6(void);
extern void STM32CubeDuinoIrqHandlerForDMA2_CH7(void);
extern void STM32CubeDuinoIrqHandlerForDMA2_CH8(void);
extern void STM32CubeDuinoIrqHandlerForDSIHOST(void);
extern void STM32CubeDuinoIrqHandlerForDTS(void);
extern void STM32CubeDuinoIrqHandlerForETH(void);
extern void STM32CubeDuinoIrqHandlerForETH1(void);
extern void STM32CubeDuinoIrqHandlerForEXTI0(void);
extern void STM32CubeDuinoIrqHandlerForEXTI1(void);
extern void STM32CubeDuinoIrqHandlerForEXTI2(void);
extern void STM32CubeDuinoIrqHandlerForEXTI3(void);
extern void STM32CubeDuinoIrqHandlerForEXTI4(void);
extern void STM32CubeDuinoIrqHandlerForEXTI5(void);
extern void STM32CubeDuinoIrqHandlerForEXTI6(void);
extern void STM32CubeDuinoIrqHandlerForEXTI7(void);
extern void STM32CubeDuinoIrqHandlerForEXTI8(void);
extern void STM32CubeDuinoIrqHandlerForEXTI9(void);
extern void STM32CubeDuinoIrqHandlerForEXTI10(void);
extern void STM32CubeDuinoIrqHandlerForEXTI11(void);
extern void STM32CubeDuinoIrqHandlerForEXTI12(void);
extern void STM32CubeDuinoIrqHandlerForEXTI13(void);
extern void STM32CubeDuinoIrqHandlerForEXTI14(void);
extern void STM32CubeDuinoIrqHandlerForEXTI15(void);
extern void STM32CubeDuinoIrqHandlerForFDCAN1(void);
extern void STM32CubeDuinoIrqHandlerForFDCAN2(void);
extern void STM32CubeDuinoIrqHandlerForFDCAN3(void);
extern void STM32CubeDuinoIrqHandlerForFLASH(void);
extern void STM32CubeDuinoIrqHandlerForFMAC(void);
extern void STM32CubeDuinoIrqHandlerForFMC(void);
extern void STM32CubeDuinoIrqHandlerForFMPI2C1(void);
extern void STM32CubeDuinoIrqHandlerForFSMC(void);
extern void STM32CubeDuinoIrqHandlerForGFXMMU(void);
extern void STM32CubeDuinoIrqHandlerForGPU(void);
extern void STM32CubeDuinoIrqHandlerForGTZC(void);
extern void STM32CubeDuinoIrqHandlerForHASH(void);
extern void STM32CubeDuinoIrqHandlerForHASH1(void);
extern void STM32CubeDuinoIrqHandlerForHASH2(void);
extern void STM32CubeDuinoIrqHandlerForHDMI_CEC(void);
extern void STM32CubeDuinoIrqHandlerForHRTIM(void);
extern void STM32CubeDuinoIrqHandlerForHRTIM1(void);
extern void STM32CubeDuinoIrqHandlerForHSEM(void);
extern void STM32CubeDuinoIrqHandlerForICACHE(void);
extern void STM32CubeDuinoIrqHandlerForIPCC(void);
extern void STM32CubeDuinoIrqHandlerForI2C1(void);
extern void STM32CubeDuinoIrqHandlerForI2C2(void);
extern void STM32CubeDuinoIrqHandlerForI2C3(void);
extern void STM32CubeDuinoIrqHandlerForI2C4(void);
extern void STM32CubeDuinoIrqHandlerForI2C5(void);
extern void STM32CubeDuinoIrqHandlerForI2C6(void);
extern void STM32CubeDuinoIrqHandlerForI2S1(void);
extern void STM32CubeDuinoIrqHandlerForI2S2(void);
extern void STM32CubeDuinoIrqHandlerForI2S3(void);
extern void STM32CubeDuinoIrqHandlerForI2S4(void);
extern void STM32CubeDuinoIrqHandlerForI2S5(void);
extern void STM32CubeDuinoIrqHandlerForI2S6(void);
extern void STM32CubeDuinoIrqHandlerForJPEG(void);
extern void STM32CubeDuinoIrqHandlerForLCD(void);
extern void STM32CubeDuinoIrqHandlerForLPTIM1(void);
extern void STM32CubeDuinoIrqHandlerForLPTIM2(void);
extern void STM32CubeDuinoIrqHandlerForLPTIM3(void);
extern void STM32CubeDuinoIrqHandlerForLPTIM4(void);
extern void STM32CubeDuinoIrqHandlerForLPTIM5(void);
extern void STM32CubeDuinoIrqHandlerForLPUART1(void);
extern void STM32CubeDuinoIrqHandlerForLPUART2(void);
extern void STM32CubeDuinoIrqHandlerForLTDC(void);
extern void STM32CubeDuinoIrqHandlerForMDIOS(void);
extern void STM32CubeDuinoIrqHandlerForMDMA(void);
extern void STM32CubeDuinoIrqHandlerForOCTOSPI1(void);
extern void STM32CubeDuinoIrqHandlerForOCTOSPI2(void);
extern void STM32CubeDuinoIrqHandlerForOTFDEC1(void);
extern void STM32CubeDuinoIrqHandlerForOTFDEC2(void);
extern void STM32CubeDuinoIrqHandlerForPKA(void);
extern void STM32CubeDuinoIrqHandlerForPSSI(void);
extern void STM32CubeDuinoIrqHandlerForPWR(void);
extern void STM32CubeDuinoIrqHandlerForQUADSPI(void);
extern void STM32CubeDuinoIrqHandlerForQUADSPI1(void);
extern void STM32CubeDuinoIrqHandlerForRCC(void);
extern void STM32CubeDuinoIrqHandlerForRNG(void);
extern void STM32CubeDuinoIrqHandlerForRNG1(void);
extern void STM32CubeDuinoIrqHandlerForRNG2(void);
extern void STM32CubeDuinoIrqHandlerForRTC(void);
extern void STM32CubeDuinoIrqHandlerForSAI1(void);
extern void STM32CubeDuinoIrqHandlerForSAI2(void);
extern void STM32CubeDuinoIrqHandlerForSAI3(void);
extern void STM32CubeDuinoIrqHandlerForSAI4(void);
extern void STM32CubeDuinoIrqHandlerForSDADC1(void);
extern void STM32CubeDuinoIrqHandlerForSDADC2(void);
extern void STM32CubeDuinoIrqHandlerForSDADC3(void);
extern void STM32CubeDuinoIrqHandlerForSDIO(void);
extern void STM32CubeDuinoIrqHandlerForSDMMC1(void);
extern void STM32CubeDuinoIrqHandlerForSDMMC2(void);
extern void STM32CubeDuinoIrqHandlerForSDMMC3(void);
extern void STM32CubeDuinoIrqHandlerForSPDIFRX(void);
extern void STM32CubeDuinoIrqHandlerForSPDIFRX1(void);
extern void STM32CubeDuinoIrqHandlerForSPI1(void);
extern void STM32CubeDuinoIrqHandlerForSPI2(void);
extern void STM32CubeDuinoIrqHandlerForSPI3(void);
extern void STM32CubeDuinoIrqHandlerForSPI4(void);
extern void STM32CubeDuinoIrqHandlerForSPI5(void);
extern void STM32CubeDuinoIrqHandlerForSPI6(void);
extern void STM32CubeDuinoIrqHandlerForSWPMI1(void);
extern void STM32CubeDuinoIrqHandlerForTAMPER(void);
extern void STM32CubeDuinoIrqHandlerForTAMP(void);
extern void STM32CubeDuinoIrqHandlerForTEMPSENS(void);
extern void STM32CubeDuinoIrqHandlerForTIM1(void);
extern void STM32CubeDuinoIrqHandlerForTIM2(void);
extern void STM32CubeDuinoIrqHandlerForTIM3(void);
extern void STM32CubeDuinoIrqHandlerForTIM4(void);
extern void STM32CubeDuinoIrqHandlerForTIM5(void);
extern void STM32CubeDuinoIrqHandlerForTIM6(void);
extern void STM32CubeDuinoIrqHandlerForTIM7(void);
extern void STM32CubeDuinoIrqHandlerForTIM8(void);
extern void STM32CubeDuinoIrqHandlerForTIM9(void);
extern void STM32CubeDuinoIrqHandlerForTIM10(void);
extern void STM32CubeDuinoIrqHandlerForTIM11(void);
extern void STM32CubeDuinoIrqHandlerForTIM12(void);
extern void STM32CubeDuinoIrqHandlerForTIM13(void);
extern void STM32CubeDuinoIrqHandlerForTIM14(void);
extern void STM32CubeDuinoIrqHandlerForTIM15(void);
extern void STM32CubeDuinoIrqHandlerForTIM16(void);
extern void STM32CubeDuinoIrqHandlerForTIM17(void);
extern void STM32CubeDuinoIrqHandlerForTIM18(void);
extern void STM32CubeDuinoIrqHandlerForTIM19(void);
extern void STM32CubeDuinoIrqHandlerForTIM20(void);
extern void STM32CubeDuinoIrqHandlerForTIM21(void);
extern void STM32CubeDuinoIrqHandlerForTIM22(void);
extern void STM32CubeDuinoIrqHandlerForTIM23(void);
extern void STM32CubeDuinoIrqHandlerForTIM24(void);
extern void STM32CubeDuinoIrqHandlerForTSC(void);
extern void STM32CubeDuinoIrqHandlerForUART4(void);
extern void STM32CubeDuinoIrqHandlerForUART5(void);
extern void STM32CubeDuinoIrqHandlerForUART7(void);
extern void STM32CubeDuinoIrqHandlerForUART8(void);
extern void STM32CubeDuinoIrqHandlerForUART9(void);
extern void STM32CubeDuinoIrqHandlerForUART10(void);
extern void STM32CubeDuinoIrqHandlerForUCPD1(void);
extern void STM32CubeDuinoIrqHandlerForUCPD2(void);
extern void STM32CubeDuinoIrqHandlerForUSART1(void);
extern void STM32CubeDuinoIrqHandlerForUSART2(void);
extern void STM32CubeDuinoIrqHandlerForUSART3(void);
extern void STM32CubeDuinoIrqHandlerForUSART4(void);
extern void STM32CubeDuinoIrqHandlerForUSART5(void);
extern void STM32CubeDuinoIrqHandlerForUSART6(void);
extern void STM32CubeDuinoIrqHandlerForUSART7(void);
extern void STM32CubeDuinoIrqHandlerForUSART8(void);
extern void STM32CubeDuinoIrqHandlerForUSART10(void);
extern void STM32CubeDuinoIrqHandlerForUSBH_HS1(void);
extern void STM32CubeDuinoIrqHandlerForUSBH_HS2(void);
extern void STM32CubeDuinoIrqHandlerForUSB_OTG_FS(void);
extern void STM32CubeDuinoIrqHandlerForUSB_OTG_HS(void);
extern void STM32CubeDuinoIrqHandlerForUSB(void);
extern void STM32CubeDuinoIrqHandlerForWWDG(void);
extern void STM32CubeDuinoIrqHandlerForWWDG1(void);
extern void STM32CubeDuinoIrqHandlerForWWDG2(void);
} /* extern "C" */


#endif /* __WIRING_IRQ_H__ */
